
target_include_directories(esmf PRIVATE ${ESMF_SOURCE_DIR}/src/Infrastructure/../include)

if(${Git_FOUND})
    string(REGEX REPLACE "^([0-9]+)\.([0-9]+)(\.[0-9]+)?$" "\\1.\\2" ESMF_VERSION_STRING_GIT ${GIT_VERSION_STRING})
    add_compile_definitions(ESMF_VERSION_STRING_GIT="${ESMF_VERSION_STRING_GIT}")
endif()
add_subdirectory(Regrid)
add_subdirectory(Container)
add_subdirectory(Array)
add_subdirectory(LocalArray)
add_subdirectory(Route)
add_subdirectory(PointList)
add_subdirectory(Trace)
add_subdirectory(FieldBundle)
add_subdirectory(Config)
add_subdirectory(HConfig)
add_subdirectory(Util)
add_subdirectory(VM)
add_subdirectory(Field)
add_subdirectory(DELayout)
add_subdirectory(stubs)
add_subdirectory(TimeMgr)
add_subdirectory(LocStream)
add_subdirectory(LogErr)
add_subdirectory(Geom)
add_subdirectory(Base)
add_subdirectory(GridUtil)
add_subdirectory(Grid)
add_subdirectory(ArraySpec)
add_subdirectory(IO)
add_subdirectory(ArrayBundle)
add_subdirectory(Mesh)
add_subdirectory(XGridGeomBase)
add_subdirectory(DistGrid)
add_subdirectory(XGrid)
