
if(${Git_FOUND})
    string(REGEX REPLACE "^([0-9]+)\.([0-9]+)(\.[0-9]+)?$" "\\1.\\2" ESMF_VERSION_STRING_GIT ${GIT_VERSION_STRING})
    add_compile_definitions(ESMF_VERSION_STRING_GIT="${ESMF_VERSION_STRING_GIT}")
endif()
add_executable(ESMF_StateReconcileUTest  ESMF_StateReconcileUTest.F90)
target_link_libraries(ESMF_StateReconcileUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMF_StateReconcileUTest OpenMP::OpenMP_Fortran)
endif()
add_executable(ESMF_StateReconcileProxyUTest  ESMF_StateReconcileProxyUTest.F90)
target_link_libraries(ESMF_StateReconcileProxyUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMF_StateReconcileProxyUTest OpenMP::OpenMP_Fortran)
endif()
add_test(RUN_ESMF_StateReconcileUTest COMMAND ESMF_StateReconcileUTest)
set_property(TEST RUN_ESMF_StateReconcileUTest PROPERTY LABEL MPI )
add_test(RUN_ESMF_StateReconcileProxyUTest COMMAND ESMF_StateReconcileProxyUTest)
set_property(TEST RUN_ESMF_StateReconcileProxyUTest PROPERTY LABEL MPI )
add_test(RUN_ESMF_StateReconcileUTestUNI COMMAND ESMF_StateReconcileUTest)
set_property(TEST RUN_ESMF_StateReconcileUTestUNI PROPERTY LABEL serial )
