
if(${Git_FOUND})
    string(REGEX REPLACE "^([0-9]+)\.([0-9]+)(\.[0-9]+)?$" "\\1.\\2" ESMF_VERSION_STRING_GIT ${GIT_VERSION_STRING})
    add_compile_definitions(ESMF_VERSION_STRING_GIT="${ESMF_VERSION_STRING_GIT}")
endif()
add_executable(ESMF_RegridWeightGenUTest  ESMF_RegridWeightGenUTest.F90)
target_link_libraries(ESMF_RegridWeightGenUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMF_RegridWeightGenUTest OpenMP::OpenMP_Fortran)
endif()
add_executable(ESMF_FileRegridUTest  ESMF_FileRegridUTest.F90)
target_link_libraries(ESMF_FileRegridUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMF_FileRegridUTest OpenMP::OpenMP_Fortran)
endif()
add_test(RUN_ESMF_RegridWeightGenUTest COMMAND ESMF_RegridWeightGenUTest)
set_property(TEST RUN_ESMF_RegridWeightGenUTest PROPERTY LABEL MPI )
add_test(RUN_ESMF_FileRegridUTest COMMAND ESMF_FileRegridUTest)
set_property(TEST RUN_ESMF_FileRegridUTest PROPERTY LABEL MPI )
add_test(RUN_ESMF_RegridWeightGenUTestUNI COMMAND ESMF_RegridWeightGenUTest)
set_property(TEST RUN_ESMF_RegridWeightGenUTestUNI PROPERTY LABEL serial )
add_test(RUN_ESMF_FileRegridUTestUNI COMMAND ESMF_FileRegridUTest)
set_property(TEST RUN_ESMF_FileRegridUTestUNI PROPERTY LABEL serial )
