
if(${Git_FOUND})
    string(REGEX REPLACE "^([0-9]+)\.([0-9]+)(\.[0-9]+)?$" "\\1.\\2" ESMF_VERSION_STRING_GIT ${GIT_VERSION_STRING})
    add_compile_definitions(ESMF_VERSION_STRING_GIT="${ESMF_VERSION_STRING_GIT}")
endif()
add_executable(ESMF_InfoGetInterfaceArrayUTest  ESMF_InfoGetInterfaceArrayUTest.F90)
target_link_libraries(ESMF_InfoGetInterfaceArrayUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMF_InfoGetInterfaceArrayUTest OpenMP::OpenMP_Fortran)
endif()
add_executable(ESMF_InfoSyncUTest  ESMF_InfoSyncUTest.F90)
target_link_libraries(ESMF_InfoSyncUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMF_InfoSyncUTest OpenMP::OpenMP_Fortran)
endif()
add_executable(ESMF_InfoDescribeUTest  ESMF_InfoDescribeUTest.F90)
target_link_libraries(ESMF_InfoDescribeUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMF_InfoDescribeUTest OpenMP::OpenMP_Fortran)
endif()
add_executable(ESMF_InfoCacheUTest  ESMF_InfoCacheUTest.F90)
target_link_libraries(ESMF_InfoCacheUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMF_InfoCacheUTest OpenMP::OpenMP_Fortran)
endif()
add_test(RUN_ESMF_InfoGetInterfaceArrayUTest COMMAND ESMF_InfoGetInterfaceArrayUTest)
set_property(TEST RUN_ESMF_InfoGetInterfaceArrayUTest PROPERTY LABEL MPI )
add_test(RUN_ESMF_InfoSyncUTest COMMAND ESMF_InfoSyncUTest)
set_property(TEST RUN_ESMF_InfoSyncUTest PROPERTY LABEL MPI )
add_test(RUN_ESMF_InfoDescribeUTest COMMAND ESMF_InfoDescribeUTest)
set_property(TEST RUN_ESMF_InfoDescribeUTest PROPERTY LABEL MPI )
add_test(RUN_ESMF_InfoCacheUTest COMMAND ESMF_InfoCacheUTest)
set_property(TEST RUN_ESMF_InfoCacheUTest PROPERTY LABEL MPI )
add_test(RUN_ESMF_InfoGetInterfaceArrayUTestUNI COMMAND ESMF_InfoGetInterfaceArrayUTest)
set_property(TEST RUN_ESMF_InfoGetInterfaceArrayUTestUNI PROPERTY LABEL serial )
add_test(RUN_ESMF_InfoSyncUTestUNI COMMAND ESMF_InfoSyncUTest)
set_property(TEST RUN_ESMF_InfoSyncUTestUNI PROPERTY LABEL serial )
add_test(RUN_ESMF_InfoDescribeUTestUNI COMMAND ESMF_InfoDescribeUTest)
set_property(TEST RUN_ESMF_InfoDescribeUTestUNI PROPERTY LABEL serial )
add_test(RUN_ESMF_InfoCacheUTestUNI COMMAND ESMF_InfoCacheUTest)
set_property(TEST RUN_ESMF_InfoCacheUTestUNI PROPERTY LABEL serial )
