
if(${Git_FOUND})
    string(REGEX REPLACE "^([0-9]+)\.([0-9]+)(\.[0-9]+)?$" "\\1.\\2" ESMF_VERSION_STRING_GIT ${GIT_VERSION_STRING})
    add_compile_definitions(ESMF_VERSION_STRING_GIT="${ESMF_VERSION_STRING_GIT}")
endif()
add_executable(ESMF_GeomUTest  ESMF_GeomUTest.F90)
target_link_libraries(ESMF_GeomUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMF_GeomUTest OpenMP::OpenMP_Fortran)
endif()
add_test(RUN_ESMF_GeomUTest COMMAND ESMF_GeomUTest)
set_property(TEST RUN_ESMF_GeomUTest PROPERTY LABEL MPI )
add_test(RUN_ESMF_GeomUTestUNI COMMAND ESMF_GeomUTest)
set_property(TEST RUN_ESMF_GeomUTestUNI PROPERTY LABEL serial )
