
if(${Git_FOUND})
    string(REGEX REPLACE "^([0-9]+)\.([0-9]+)(\.[0-9]+)?$" "\\1.\\2" ESMF_VERSION_STRING_GIT ${GIT_VERSION_STRING})
    add_compile_definitions(ESMF_VERSION_STRING_GIT="${ESMF_VERSION_STRING_GIT}")
endif()
add_executable(ESMF_FieldBundleUTest  ESMF_FieldBundleUTest.F90)
target_link_libraries(ESMF_FieldBundleUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMF_FieldBundleUTest OpenMP::OpenMP_Fortran)
endif()
add_executable(ESMF_FieldBundleCrGetUTest  ESMF_FieldBundleCrGetUTest.F90)
target_link_libraries(ESMF_FieldBundleCrGetUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMF_FieldBundleCrGetUTest OpenMP::OpenMP_Fortran)
endif()
add_executable(ESMF_FieldBundleRedistUTest  ESMF_FieldBundleRedistUTest.F90)
target_link_libraries(ESMF_FieldBundleRedistUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMF_FieldBundleRedistUTest OpenMP::OpenMP_Fortran)
endif()
add_executable(ESMF_FieldBundleSMMUTest  ESMF_FieldBundleSMMUTest.F90)
target_link_libraries(ESMF_FieldBundleSMMUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMF_FieldBundleSMMUTest OpenMP::OpenMP_Fortran)
endif()
add_executable(ESMF_FieldBundleIOUTest  ESMF_FieldBundleIOUTest.F90)
target_link_libraries(ESMF_FieldBundleIOUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMF_FieldBundleIOUTest OpenMP::OpenMP_Fortran)
endif()
add_executable(ESMF_FieldBundleRegridUTest  ESMF_FieldBundleRegridUTest.F90)
target_link_libraries(ESMF_FieldBundleRegridUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMF_FieldBundleRegridUTest OpenMP::OpenMP_Fortran)
endif()
add_test(RUN_ESMF_FieldBundleUTest COMMAND ESMF_FieldBundleUTest)
set_property(TEST RUN_ESMF_FieldBundleUTest PROPERTY LABEL MPI )
add_test(RUN_ESMF_FieldBundleCrGetUTest COMMAND ESMF_FieldBundleCrGetUTest)
set_property(TEST RUN_ESMF_FieldBundleCrGetUTest PROPERTY LABEL MPI )
add_test(RUN_ESMF_FieldBundleRedistUTest COMMAND ESMF_FieldBundleRedistUTest)
set_property(TEST RUN_ESMF_FieldBundleRedistUTest PROPERTY LABEL MPI )
add_test(RUN_ESMF_FieldBundleSMMUTest COMMAND ESMF_FieldBundleSMMUTest)
set_property(TEST RUN_ESMF_FieldBundleSMMUTest PROPERTY LABEL MPI )
add_test(RUN_ESMF_FieldBundleIOUTest COMMAND ESMF_FieldBundleIOUTest)
set_property(TEST RUN_ESMF_FieldBundleIOUTest PROPERTY LABEL MPI )
add_test(RUN_ESMF_FieldBundleRegridUTest COMMAND ESMF_FieldBundleRegridUTest)
set_property(TEST RUN_ESMF_FieldBundleRegridUTest PROPERTY LABEL MPI )
add_test(RUN_ESMF_FieldBundleUTestUNI COMMAND ESMF_FieldBundleUTest)
set_property(TEST RUN_ESMF_FieldBundleUTestUNI PROPERTY LABEL serial )
add_test(RUN_ESMF_FieldBundleRegridUTestUNI COMMAND ESMF_FieldBundleRegridUTest)
set_property(TEST RUN_ESMF_FieldBundleRegridUTestUNI PROPERTY LABEL serial )
