
target_include_directories(esmf PRIVATE ${ESMF_SOURCE_DIR}/src/Infrastructure/Util/tests/../include)

if(${Git_FOUND})
    string(REGEX REPLACE "^([0-9]+)\.([0-9]+)(\.[0-9]+)?$" "\\1.\\2" ESMF_VERSION_STRING_GIT ${GIT_VERSION_STRING})
    add_compile_definitions(ESMF_VERSION_STRING_GIT="${ESMF_VERSION_STRING_GIT}")
endif()
add_executable(ESMF_UtilUTest  ESMF_UtilUTest.F90)
target_link_libraries(ESMF_UtilUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMF_UtilUTest OpenMP::OpenMP_Fortran)
endif()
add_executable(ESMF_FortranWordsizeUTest  ESMF_FortranWordsizeUTest.F90)
target_link_libraries(ESMF_FortranWordsizeUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMF_FortranWordsizeUTest OpenMP::OpenMP_Fortran)
endif()
add_executable(ESMF_TypeKindGetUTest  ESMF_TypeKindGetUTest.F90)
target_link_libraries(ESMF_TypeKindGetUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMF_TypeKindGetUTest OpenMP::OpenMP_Fortran)
endif()
add_executable(ESMF_InitMacrosUTest  ESMF_InitMacrosTestTypes.F90 ESMF_InitMacrosUTest.F90)
target_link_libraries(ESMF_InitMacrosUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMF_InitMacrosUTest OpenMP::OpenMP_Fortran)
endif()
add_test(RUN_ESMF_UtilUTest COMMAND ESMF_UtilUTest)
set_property(TEST RUN_ESMF_UtilUTest PROPERTY LABEL MPI )
add_test(RUN_ESMF_FortranWordsizeUTest COMMAND ESMF_FortranWordsizeUTest)
set_property(TEST RUN_ESMF_FortranWordsizeUTest PROPERTY LABEL MPI )
add_test(RUN_ESMF_TypeKindGetUTest COMMAND ESMF_TypeKindGetUTest)
set_property(TEST RUN_ESMF_TypeKindGetUTest PROPERTY LABEL MPI )
add_test(RUN_ESMF_InitMacrosUTest COMMAND ESMF_InitMacrosUTest)
set_property(TEST RUN_ESMF_InitMacrosUTest PROPERTY LABEL MPI )
add_test(RUN_ESMF_UtilUTestUNI COMMAND ESMF_UtilUTest)
set_property(TEST RUN_ESMF_UtilUTestUNI PROPERTY LABEL serial )
add_test(RUN_ESMF_FortranWordsizeUTestUNI COMMAND ESMF_FortranWordsizeUTest)
set_property(TEST RUN_ESMF_FortranWordsizeUTestUNI PROPERTY LABEL serial )
add_test(RUN_ESMF_TypeKindGetUTestUNI COMMAND ESMF_TypeKindGetUTest)
set_property(TEST RUN_ESMF_TypeKindGetUTestUNI PROPERTY LABEL serial )
add_test(RUN_ESMF_InitMacrosUTestUNI COMMAND ESMF_InitMacrosUTest)
set_property(TEST RUN_ESMF_InitMacrosUTestUNI PROPERTY LABEL serial )
