
target_include_directories(esmf PRIVATE ${ESMF_SOURCE_DIR}/src/Infrastructure/Trace/tests/../include)

if(${Git_FOUND})
    string(REGEX REPLACE "^([0-9]+)\.([0-9]+)(\.[0-9]+)?$" "\\1.\\2" ESMF_VERSION_STRING_GIT ${GIT_VERSION_STRING})
    add_compile_definitions(ESMF_VERSION_STRING_GIT="${ESMF_VERSION_STRING_GIT}")
endif()
add_executable(ESMF_TraceClkMonoUTest  ESMF_TraceClkMonoUTest.F90)
target_link_libraries(ESMF_TraceClkMonoUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMF_TraceClkMonoUTest OpenMP::OpenMP_Fortran)
endif()
add_executable(ESMF_TraceClkMonoSyncUTest  ESMF_TraceClkMonoSyncUTest.F90)
target_link_libraries(ESMF_TraceClkMonoSyncUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMF_TraceClkMonoSyncUTest OpenMP::OpenMP_Fortran)
endif()
add_executable(ESMF_TraceUTest  ESMF_TraceUTest.F90 ESMF_SimpleComp.F90)
target_link_libraries(ESMF_TraceUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMF_TraceUTest OpenMP::OpenMP_Fortran)
endif()
add_executable(ESMF_TraceIOUTest  ESMF_TraceIOUTest.F90)
target_link_libraries(ESMF_TraceIOUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMF_TraceIOUTest OpenMP::OpenMP_Fortran)
endif()
add_executable(ESMF_TraceMPIUTest  ESMF_TraceMPIUTest.F90)
target_link_libraries(ESMF_TraceMPIUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMF_TraceMPIUTest OpenMP::OpenMP_Fortran)
endif()
add_executable(ESMCI_TraceRegionUTest  ESMCI_TraceRegionUTest.C)
target_link_libraries(ESMCI_TraceRegionUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMCI_TraceRegionUTest OpenMP::OpenMP_CXX)
endif()
add_executable(ESMC_TraceRegionUTest  ESMC_TraceRegionUTest.c)
target_link_libraries(ESMC_TraceRegionUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMC_TraceRegionUTest OpenMP::OpenMP_C)
endif()
add_executable(ESMF_ProfileUTest  ESMF_ProfileUTest.F90 ESMF_SimpleCompB.F90)
target_link_libraries(ESMF_ProfileUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMF_ProfileUTest OpenMP::OpenMP_Fortran)
endif()
add_test(RUN_ESMF_TraceUTest COMMAND ESMF_TraceUTest)
set_property(TEST RUN_ESMF_TraceUTest PROPERTY LABEL MPI )
add_test(RUN_ESMF_TraceClkMonoUTest COMMAND ESMF_TraceClkMonoUTest)
set_property(TEST RUN_ESMF_TraceClkMonoUTest PROPERTY LABEL MPI )
add_test(RUN_ESMF_TraceClkMonoSyncUTest COMMAND ESMF_TraceClkMonoSyncUTest)
set_property(TEST RUN_ESMF_TraceClkMonoSyncUTest PROPERTY LABEL MPI )
add_test(RUN_ESMF_TraceIOUTest COMMAND ESMF_TraceIOUTest)
set_property(TEST RUN_ESMF_TraceIOUTest PROPERTY LABEL MPI )
add_test(RUN_ESMF_TraceMPIUTest COMMAND ESMF_TraceMPIUTest)
set_property(TEST RUN_ESMF_TraceMPIUTest PROPERTY LABEL MPI )
add_test(RUN_ESMCI_TraceRegionUTest COMMAND ESMCI_TraceRegionUTest)
set_property(TEST RUN_ESMCI_TraceRegionUTest PROPERTY LABEL MPI )
add_test(RUN_ESMC_TraceRegionUTest COMMAND ESMC_TraceRegionUTest)
set_property(TEST RUN_ESMC_TraceRegionUTest PROPERTY LABEL MPI )
add_test(RUN_ESMF_ProfileUTest COMMAND ESMF_ProfileUTest)
set_property(TEST RUN_ESMF_ProfileUTest PROPERTY LABEL MPI )
add_test(RUN_ESMF_TraceUTestUNI COMMAND ESMF_TraceUTest)
set_property(TEST RUN_ESMF_TraceUTestUNI PROPERTY LABEL serial )
add_test(RUN_ESMF_TraceClkMonoUTestUNI COMMAND ESMF_TraceClkMonoUTest)
set_property(TEST RUN_ESMF_TraceClkMonoUTestUNI PROPERTY LABEL serial )
add_test(RUN_ESMF_TraceClkMonoSyncUTestUNI COMMAND ESMF_TraceClkMonoSyncUTest)
set_property(TEST RUN_ESMF_TraceClkMonoSyncUTestUNI PROPERTY LABEL serial )
add_test(RUN_ESMF_TraceIOUTestUNI COMMAND ESMF_TraceIOUTest)
set_property(TEST RUN_ESMF_TraceIOUTestUNI PROPERTY LABEL serial )
add_test(RUN_ESMF_TraceMPIUTestUNI COMMAND ESMF_TraceMPIUTest)
set_property(TEST RUN_ESMF_TraceMPIUTestUNI PROPERTY LABEL serial )
add_test(RUN_ESMCI_TraceRegionUTestUNI COMMAND ESMCI_TraceRegionUTest)
set_property(TEST RUN_ESMCI_TraceRegionUTestUNI PROPERTY LABEL serial )
add_test(RUN_ESMC_TraceRegionUTestUNI COMMAND ESMC_TraceRegionUTest)
set_property(TEST RUN_ESMC_TraceRegionUTestUNI PROPERTY LABEL serial )
add_test(RUN_ESMF_ProfileUTestUNI COMMAND ESMF_ProfileUTest)
set_property(TEST RUN_ESMF_ProfileUTestUNI PROPERTY LABEL serial )
