
target_include_directories(esmf PRIVATE ${ESMF_SOURCE_DIR}/src/Infrastructure/TimeMgr/tests/../include)

if(${Git_FOUND})
    string(REGEX REPLACE "^([0-9]+)\.([0-9]+)(\.[0-9]+)?$" "\\1.\\2" ESMF_VERSION_STRING_GIT ${GIT_VERSION_STRING})
    add_compile_definitions(ESMF_VERSION_STRING_GIT="${ESMF_VERSION_STRING_GIT}")
endif()
add_executable(ESMC_ClockUTest  ESMC_ClockUTest.c)
target_link_libraries(ESMC_ClockUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMC_ClockUTest OpenMP::OpenMP_C)
endif()
add_executable(ESMC_TimeIntervalUTest  ESMC_TimeIntervalUTest.c)
target_link_libraries(ESMC_TimeIntervalUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMC_TimeIntervalUTest OpenMP::OpenMP_C)
endif()
add_executable(ESMC_TimeUTest  ESMC_TimeUTest.c)
target_link_libraries(ESMC_TimeUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMC_TimeUTest OpenMP::OpenMP_C)
endif()
add_executable(ESMC_CalendarUTest  ESMC_CalendarUTest.c)
target_link_libraries(ESMC_CalendarUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMC_CalendarUTest OpenMP::OpenMP_C)
endif()
add_executable(ESMF_CalendarUTest  ESMF_CalendarUTest.F90)
target_link_libraries(ESMF_CalendarUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMF_CalendarUTest OpenMP::OpenMP_Fortran)
endif()
add_executable(ESMF_AlarmUTest  ESMF_AlarmUTest.F90)
target_link_libraries(ESMF_AlarmUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMF_AlarmUTest OpenMP::OpenMP_Fortran)
endif()
add_executable(ESMF_ClockUTest  ESMF_ClockUTest.F90)
target_link_libraries(ESMF_ClockUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMF_ClockUTest OpenMP::OpenMP_Fortran)
endif()
add_executable(ESMF_CalRangeUTest  ESMF_CalRangeUTest.F90)
target_link_libraries(ESMF_CalRangeUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMF_CalRangeUTest OpenMP::OpenMP_Fortran)
endif()
add_executable(ESMF_TimeIntervalUTest  ESMF_TimeIntervalUTest.F90)
target_link_libraries(ESMF_TimeIntervalUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMF_TimeIntervalUTest OpenMP::OpenMP_Fortran)
endif()
add_executable(ESMF_TimeUTest  ESMF_TimeUTest.F90)
target_link_libraries(ESMF_TimeUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMF_TimeUTest OpenMP::OpenMP_Fortran)
endif()
add_test(RUN_ESMC_ClockUTest COMMAND ESMC_ClockUTest)
set_property(TEST RUN_ESMC_ClockUTest PROPERTY LABEL MPI )
add_test(RUN_ESMC_TimeIntervalUTest COMMAND ESMC_TimeIntervalUTest)
set_property(TEST RUN_ESMC_TimeIntervalUTest PROPERTY LABEL MPI )
add_test(RUN_ESMC_TimeUTest COMMAND ESMC_TimeUTest)
set_property(TEST RUN_ESMC_TimeUTest PROPERTY LABEL MPI )
add_test(RUN_ESMC_CalendarUTest COMMAND ESMC_CalendarUTest)
set_property(TEST RUN_ESMC_CalendarUTest PROPERTY LABEL MPI )
add_test(RUN_ESMF_AlarmUTest COMMAND ESMF_AlarmUTest)
set_property(TEST RUN_ESMF_AlarmUTest PROPERTY LABEL MPI )
add_test(RUN_ESMF_CalendarUTest COMMAND ESMF_CalendarUTest)
set_property(TEST RUN_ESMF_CalendarUTest PROPERTY LABEL MPI )
add_test(RUN_ESMF_ClockUTest COMMAND ESMF_ClockUTest)
set_property(TEST RUN_ESMF_ClockUTest PROPERTY LABEL MPI )
add_test(RUN_ESMF_CalRangeUTest COMMAND ESMF_CalRangeUTest)
set_property(TEST RUN_ESMF_CalRangeUTest PROPERTY LABEL MPI )
add_test(RUN_ESMF_TimeIntervalUTest COMMAND ESMF_TimeIntervalUTest)
set_property(TEST RUN_ESMF_TimeIntervalUTest PROPERTY LABEL MPI )
add_test(RUN_ESMF_TimeUTest COMMAND ESMF_TimeUTest)
set_property(TEST RUN_ESMF_TimeUTest PROPERTY LABEL MPI )
add_test(RUN_ESMC_ClockUTestUNI COMMAND ESMC_ClockUTest)
set_property(TEST RUN_ESMC_ClockUTestUNI PROPERTY LABEL serial )
add_test(RUN_ESMC_TimeIntervalUTestUNI COMMAND ESMC_TimeIntervalUTest)
set_property(TEST RUN_ESMC_TimeIntervalUTestUNI PROPERTY LABEL serial )
add_test(RUN_ESMC_TimeUTestUNI COMMAND ESMC_TimeUTest)
set_property(TEST RUN_ESMC_TimeUTestUNI PROPERTY LABEL serial )
add_test(RUN_ESMC_CalendarUTestUNI COMMAND ESMC_CalendarUTest)
set_property(TEST RUN_ESMC_CalendarUTestUNI PROPERTY LABEL serial )
add_test(RUN_ESMF_AlarmUTestUNI COMMAND ESMF_AlarmUTest)
set_property(TEST RUN_ESMF_AlarmUTestUNI PROPERTY LABEL serial )
add_test(RUN_ESMF_CalendarUTestUNI COMMAND ESMF_CalendarUTest)
set_property(TEST RUN_ESMF_CalendarUTestUNI PROPERTY LABEL serial )
add_test(RUN_ESMF_ClockUTestUNI COMMAND ESMF_ClockUTest)
set_property(TEST RUN_ESMF_ClockUTestUNI PROPERTY LABEL serial )
add_test(RUN_ESMF_CalRangeUTestUNI COMMAND ESMF_CalRangeUTest)
set_property(TEST RUN_ESMF_CalRangeUTestUNI PROPERTY LABEL serial )
add_test(RUN_ESMF_TimeIntervalUTestUNI COMMAND ESMF_TimeIntervalUTest)
set_property(TEST RUN_ESMF_TimeIntervalUTestUNI PROPERTY LABEL serial )
add_test(RUN_ESMF_TimeUTestUNI COMMAND ESMF_TimeUTest)
set_property(TEST RUN_ESMF_TimeUTestUNI PROPERTY LABEL serial )
