
target_include_directories(esmf PRIVATE ${ESMF_SOURCE_DIR}/src/Superstructure/State/tests/../include)

if(${Git_FOUND})
    string(REGEX REPLACE "^([0-9]+)\.([0-9]+)(\.[0-9]+)?$" "\\1.\\2" ESMF_VERSION_STRING_GIT ${GIT_VERSION_STRING})
    add_compile_definitions(ESMF_VERSION_STRING_GIT="${ESMF_VERSION_STRING_GIT}")
endif()
add_executable(ESMC_StateUTest  ESMC_StateUTest.c)
target_link_libraries(ESMC_StateUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMC_StateUTest OpenMP::OpenMP_C)
endif()
add_executable(ESMF_StateCreateUTest  ESMF_StateCreateUTest.F90)
target_link_libraries(ESMF_StateCreateUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMF_StateCreateUTest OpenMP::OpenMP_Fortran)
endif()
add_executable(ESMF_StateUTest  ESMF_StateUTest.F90)
target_link_libraries(ESMF_StateUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMF_StateUTest OpenMP::OpenMP_Fortran)
endif()
add_test(RUN_ESMC_StateUTest COMMAND ESMC_StateUTest)
set_property(TEST RUN_ESMC_StateUTest PROPERTY LABEL MPI )
add_test(RUN_ESMF_StateCreateUTest COMMAND ESMF_StateCreateUTest)
set_property(TEST RUN_ESMF_StateCreateUTest PROPERTY LABEL MPI )
add_test(RUN_ESMF_StateUTest COMMAND ESMF_StateUTest)
set_property(TEST RUN_ESMF_StateUTest PROPERTY LABEL MPI )
add_test(RUN_ESMC_StateUTestUNI COMMAND ESMC_StateUTest)
set_property(TEST RUN_ESMC_StateUTestUNI PROPERTY LABEL serial )
add_test(RUN_ESMF_StateCreateUTestUNI COMMAND ESMF_StateCreateUTest)
set_property(TEST RUN_ESMF_StateCreateUTestUNI PROPERTY LABEL serial )
add_test(RUN_ESMF_StateUTestUNI COMMAND ESMF_StateUTest)
set_property(TEST RUN_ESMF_StateUTestUNI PROPERTY LABEL serial )
