
target_include_directories(esmf PRIVATE ${ESMF_SOURCE_DIR}/src/Infrastructure/VM/tests/../include)

if(${Git_FOUND})
    string(REGEX REPLACE "^([0-9]+)\.([0-9]+)(\.[0-9]+)?$" "\\1.\\2" ESMF_VERSION_STRING_GIT ${GIT_VERSION_STRING})
    add_compile_definitions(ESMF_VERSION_STRING_GIT="${ESMF_VERSION_STRING_GIT}")
endif()
add_executable(ESMC_VMUTest  ESMC_VMUTest.c)
target_link_libraries(ESMC_VMUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMC_VMUTest OpenMP::OpenMP_C)
endif()
add_executable(ESMF_VMUTest  ESMF_VMUTest.F90)
target_link_libraries(ESMF_VMUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMF_VMUTest OpenMP::OpenMP_Fortran)
endif()
add_executable(ESMF_VMAccUTest  ESMF_VMAccUTest.F90)
target_link_libraries(ESMF_VMAccUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMF_VMAccUTest OpenMP::OpenMP_Fortran)
endif()
add_executable(ESMF_VMOpenMPUTest  ESMF_VMOpenMPUTest.F90)
target_link_libraries(ESMF_VMOpenMPUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMF_VMOpenMPUTest OpenMP::OpenMP_Fortran)
endif()
add_executable(ESMF_VMUserMpiInitUTest  ESMF_VMUserMpiInitUTest.F90)
target_link_libraries(ESMF_VMUserMpiInitUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMF_VMUserMpiInitUTest OpenMP::OpenMP_Fortran)
endif()
add_executable(ESMF_VMSendVMRecvUTest  ESMF_VMSendVMRecvUTest.F90)
target_link_libraries(ESMF_VMSendVMRecvUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMF_VMSendVMRecvUTest OpenMP::OpenMP_Fortran)
endif()
add_executable(ESMF_VMSendNbVMRecvNbUTest  ESMF_VMSendNbVMRecvNbUTest.F90)
target_link_libraries(ESMF_VMSendNbVMRecvNbUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMF_VMSendNbVMRecvNbUTest OpenMP::OpenMP_Fortran)
endif()
add_executable(ESMF_VMSendRecvUTest  ESMF_VMSendRecvUTest.F90)
target_link_libraries(ESMF_VMSendRecvUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMF_VMSendRecvUTest OpenMP::OpenMP_Fortran)
endif()
add_executable(ESMF_VMSendRecvNbUTest  ESMF_VMSendRecvNbUTest.F90)
target_link_libraries(ESMF_VMSendRecvNbUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMF_VMSendRecvNbUTest OpenMP::OpenMP_Fortran)
endif()
add_executable(ESMF_VMScatterUTest  ESMF_VMScatterUTest.F90)
target_link_libraries(ESMF_VMScatterUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMF_VMScatterUTest OpenMP::OpenMP_Fortran)
endif()
add_executable(ESMF_VMGatherUTest  ESMF_VMGatherUTest.F90)
target_link_libraries(ESMF_VMGatherUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMF_VMGatherUTest OpenMP::OpenMP_Fortran)
endif()
add_executable(ESMF_VMAllGatherUTest  ESMF_VMAllGatherUTest.F90)
target_link_libraries(ESMF_VMAllGatherUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMF_VMAllGatherUTest OpenMP::OpenMP_Fortran)
endif()
add_executable(ESMF_VMAllGatherVUTest  ESMF_VMAllGatherVUTest.F90)
target_link_libraries(ESMF_VMAllGatherVUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMF_VMAllGatherVUTest OpenMP::OpenMP_Fortran)
endif()
add_executable(ESMF_VMBroadcastUTest  ESMF_VMBroadcastUTest.F90)
target_link_libraries(ESMF_VMBroadcastUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMF_VMBroadcastUTest OpenMP::OpenMP_Fortran)
endif()
add_executable(ESMF_VMAllToAllUTest  ESMF_VMAllToAllUTest.F90)
target_link_libraries(ESMF_VMAllToAllUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMF_VMAllToAllUTest OpenMP::OpenMP_Fortran)
endif()
add_executable(ESMF_VMAllToAllVUTest  ESMF_VMAllToAllVUTest.F90)
target_link_libraries(ESMF_VMAllToAllVUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMF_VMAllToAllVUTest OpenMP::OpenMP_Fortran)
endif()
add_executable(ESMF_VMBarrierUTest  ESMF_VMBarrierUTest.F90)
target_link_libraries(ESMF_VMBarrierUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMF_VMBarrierUTest OpenMP::OpenMP_Fortran)
endif()
add_executable(ESMF_VMEpochLargeMsgUTest  ESMF_VMEpochLargeMsgUTest.F90)
target_link_libraries(ESMF_VMEpochLargeMsgUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMF_VMEpochLargeMsgUTest OpenMP::OpenMP_Fortran)
endif()
add_executable(ESMF_VMComponentUTest  ESMF_VMComponentUTest.F90)
target_link_libraries(ESMF_VMComponentUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMF_VMComponentUTest OpenMP::OpenMP_Fortran)
endif()
add_test(RUN_ESMC_VMUTest COMMAND ESMC_VMUTest)
set_property(TEST RUN_ESMC_VMUTest PROPERTY LABEL MPI )
add_test(RUN_ESMF_VMUTest COMMAND ESMF_VMUTest)
set_property(TEST RUN_ESMF_VMUTest PROPERTY LABEL MPI )
add_test(RUN_ESMF_VMAccUTest COMMAND ESMF_VMAccUTest)
set_property(TEST RUN_ESMF_VMAccUTest PROPERTY LABEL MPI )
add_test(RUN_ESMF_VMOpenMPUTest COMMAND ESMF_VMOpenMPUTest)
set_property(TEST RUN_ESMF_VMOpenMPUTest PROPERTY LABEL MPI )
add_test(RUN_ESMF_VMUserMpiInitUTest COMMAND ESMF_VMUserMpiInitUTest)
set_property(TEST RUN_ESMF_VMUserMpiInitUTest PROPERTY LABEL MPI )
add_test(RUN_ESMF_VMSendVMRecvUTest COMMAND ESMF_VMSendVMRecvUTest)
set_property(TEST RUN_ESMF_VMSendVMRecvUTest PROPERTY LABEL MPI )
add_test(RUN_ESMF_VMSendNbVMRecvNbUTest COMMAND ESMF_VMSendNbVMRecvNbUTest)
set_property(TEST RUN_ESMF_VMSendNbVMRecvNbUTest PROPERTY LABEL MPI )
add_test(RUN_ESMF_VMSendRecvUTest COMMAND ESMF_VMSendRecvUTest)
set_property(TEST RUN_ESMF_VMSendRecvUTest PROPERTY LABEL MPI )
add_test(RUN_ESMF_VMSendRecvNbUTest COMMAND ESMF_VMSendRecvNbUTest)
set_property(TEST RUN_ESMF_VMSendRecvNbUTest PROPERTY LABEL MPI )
add_test(RUN_ESMF_VMScatterUTest COMMAND ESMF_VMScatterUTest)
set_property(TEST RUN_ESMF_VMScatterUTest PROPERTY LABEL MPI )
add_test(RUN_ESMF_VMGatherUTest COMMAND ESMF_VMGatherUTest)
set_property(TEST RUN_ESMF_VMGatherUTest PROPERTY LABEL MPI )
add_test(RUN_ESMF_VMAllGatherUTest COMMAND ESMF_VMAllGatherUTest)
set_property(TEST RUN_ESMF_VMAllGatherUTest PROPERTY LABEL MPI )
add_test(RUN_ESMF_VMAllGatherVUTest COMMAND ESMF_VMAllGatherVUTest)
set_property(TEST RUN_ESMF_VMAllGatherVUTest PROPERTY LABEL MPI )
add_test(RUN_ESMF_VMBroadcastUTest COMMAND ESMF_VMBroadcastUTest)
set_property(TEST RUN_ESMF_VMBroadcastUTest PROPERTY LABEL MPI )
add_test(RUN_ESMF_VMAllToAllUTest COMMAND ESMF_VMAllToAllUTest)
set_property(TEST RUN_ESMF_VMAllToAllUTest PROPERTY LABEL MPI )
add_test(RUN_ESMF_VMAllToAllVUTest COMMAND ESMF_VMAllToAllVUTest)
set_property(TEST RUN_ESMF_VMAllToAllVUTest PROPERTY LABEL MPI )
add_test(RUN_ESMF_VMBarrierUTest COMMAND ESMF_VMBarrierUTest)
set_property(TEST RUN_ESMF_VMBarrierUTest PROPERTY LABEL MPI )
add_test(RUN_ESMF_VMEpochLargeMsgUTest COMMAND ESMF_VMEpochLargeMsgUTest)
set_property(TEST RUN_ESMF_VMEpochLargeMsgUTest PROPERTY LABEL MPI )
add_test(RUN_ESMF_VMComponentUTest COMMAND ESMF_VMComponentUTest)
set_property(TEST RUN_ESMF_VMComponentUTest PROPERTY LABEL MPI )
add_test(RUN_ESMC_VMUTestUNI COMMAND ESMC_VMUTest)
set_property(TEST RUN_ESMC_VMUTestUNI PROPERTY LABEL serial )
add_test(RUN_ESMF_VMUTestUNI COMMAND ESMF_VMUTest)
set_property(TEST RUN_ESMF_VMUTestUNI PROPERTY LABEL serial )
add_test(RUN_ESMF_VMAccUTestUNI COMMAND ESMF_VMAccUTest)
set_property(TEST RUN_ESMF_VMAccUTestUNI PROPERTY LABEL serial )
add_test(RUN_ESMF_VMOpenMPUTestUNI COMMAND ESMF_VMOpenMPUTest)
set_property(TEST RUN_ESMF_VMOpenMPUTestUNI PROPERTY LABEL serial )
add_test(RUN_ESMF_VMUserMpiInitUTestUNI COMMAND ESMF_VMUserMpiInitUTest)
set_property(TEST RUN_ESMF_VMUserMpiInitUTestUNI PROPERTY LABEL serial )
add_test(RUN_ESMF_VMSendNbVMRecvNbUTestUNI COMMAND ESMF_VMSendNbVMRecvNbUTest)
set_property(TEST RUN_ESMF_VMSendNbVMRecvNbUTestUNI PROPERTY LABEL serial )
add_test(RUN_ESMF_VMSendRecvUTestUNI COMMAND ESMF_VMSendRecvUTest)
set_property(TEST RUN_ESMF_VMSendRecvUTestUNI PROPERTY LABEL serial )
add_test(RUN_ESMF_VMSendRecvNbUTestUNI COMMAND ESMF_VMSendRecvNbUTest)
set_property(TEST RUN_ESMF_VMSendRecvNbUTestUNI PROPERTY LABEL serial )
add_test(RUN_ESMF_VMScatterUTestUNI COMMAND ESMF_VMScatterUTest)
set_property(TEST RUN_ESMF_VMScatterUTestUNI PROPERTY LABEL serial )
add_test(RUN_ESMF_VMGatherUTestUNI COMMAND ESMF_VMGatherUTest)
set_property(TEST RUN_ESMF_VMGatherUTestUNI PROPERTY LABEL serial )
add_test(RUN_ESMF_VMAllGatherUTestUNI COMMAND ESMF_VMAllGatherUTest)
set_property(TEST RUN_ESMF_VMAllGatherUTestUNI PROPERTY LABEL serial )
add_test(RUN_ESMF_VMAllGatherVUTestUNI COMMAND ESMF_VMAllGatherVUTest)
set_property(TEST RUN_ESMF_VMAllGatherVUTestUNI PROPERTY LABEL serial )
add_test(RUN_ESMF_VMBroadcastUTestUNI COMMAND ESMF_VMBroadcastUTest)
set_property(TEST RUN_ESMF_VMBroadcastUTestUNI PROPERTY LABEL serial )
add_test(RUN_ESMF_VMAllToAllUTestUNI COMMAND ESMF_VMAllToAllUTest)
set_property(TEST RUN_ESMF_VMAllToAllUTestUNI PROPERTY LABEL serial )
add_test(RUN_ESMF_VMAllToAllVUTestUNI COMMAND ESMF_VMAllToAllVUTest)
set_property(TEST RUN_ESMF_VMAllToAllVUTestUNI PROPERTY LABEL serial )
add_test(RUN_ESMF_VMBarrierUTestUNI COMMAND ESMF_VMBarrierUTest)
set_property(TEST RUN_ESMF_VMBarrierUTestUNI PROPERTY LABEL serial )
add_test(RUN_ESMF_VMComponentUTestUNI COMMAND ESMF_VMComponentUTest)
set_property(TEST RUN_ESMF_VMComponentUTestUNI PROPERTY LABEL serial )
