
if(${Git_FOUND})
    string(REGEX REPLACE "^([0-9]+)\.([0-9]+)(\.[0-9]+)?$" "\\1.\\2" ESMF_VERSION_STRING_GIT ${GIT_VERSION_STRING})
    add_compile_definitions(ESMF_VERSION_STRING_GIT="${ESMF_VERSION_STRING_GIT}")
endif()
add_executable(ESMF_NamedAliasUTest  ESMF_NamedAliasUTest.F90)
target_link_libraries(ESMF_NamedAliasUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMF_NamedAliasUTest OpenMP::OpenMP_Fortran)
endif()
add_test(RUN_ESMF_NamedAliasUTest COMMAND ESMF_NamedAliasUTest)
set_property(TEST RUN_ESMF_NamedAliasUTest PROPERTY LABEL MPI )
add_test(RUN_ESMF_NamedAliasUTestUNI COMMAND ESMF_NamedAliasUTest)
set_property(TEST RUN_ESMF_NamedAliasUTestUNI PROPERTY LABEL serial )
