
if(${Git_FOUND})
    string(REGEX REPLACE "^([0-9]+)\.([0-9]+)(\.[0-9]+)?$" "\\1.\\2" ESMF_VERSION_STRING_GIT ${GIT_VERSION_STRING})
    add_compile_definitions(ESMF_VERSION_STRING_GIT="${ESMF_VERSION_STRING_GIT}")
endif()
add_executable(ESMF_StringUTest  ESMF_StringUTest.F90 ESMCI_StringSubr.C)
target_link_libraries(ESMF_StringUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMF_StringUTest OpenMP::OpenMP_Fortran)
target_link_libraries(ESMF_StringUTest OpenMP::OpenMP_CXX)
endif()
add_executable(ESMF_WordsizeUTest  ESMCI_WordsizeSubr.C ESMF_WordsizeUTest.F90)
target_link_libraries(ESMF_WordsizeUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMF_WordsizeUTest OpenMP::OpenMP_Fortran)
target_link_libraries(ESMF_WordsizeUTest OpenMP::OpenMP_CXX)
endif()
add_executable(ESMF_F90ArrayPtrUTest  ESMF_F90ArrayPtrUTest.F90)
target_link_libraries(ESMF_F90ArrayPtrUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMF_F90ArrayPtrUTest OpenMP::OpenMP_Fortran)
endif()
add_executable(ESMF_LAPACKUTest  ESMF_LAPACKUTest.F90)
target_link_libraries(ESMF_LAPACKUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMF_LAPACKUTest OpenMP::OpenMP_Fortran)
endif()
add_executable(ESMF_FeatureUTest  ESMF_FeatureTR15581Subr.F90 ESMF_FeatureUTest.F90 ESMCI_FeatureSubr.C)
target_link_libraries(ESMF_FeatureUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMF_FeatureUTest OpenMP::OpenMP_Fortran)
target_link_libraries(ESMF_FeatureUTest OpenMP::OpenMP_CXX)
endif()
add_executable(ESMF_ExceptionsUTest  ESMCI_ExceptionsSubr.C ESMF_ExceptionsUTest.F90)
target_link_libraries(ESMF_ExceptionsUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMF_ExceptionsUTest OpenMP::OpenMP_Fortran)
target_link_libraries(ESMF_ExceptionsUTest OpenMP::OpenMP_CXX)
endif()
add_executable(ESMCI_ExceptionsUTest  ESMCI_ExceptionsUTest.C ESMCI_ExceptionsSubr.C)
target_link_libraries(ESMCI_ExceptionsUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMCI_ExceptionsUTest OpenMP::OpenMP_CXX)
endif()
add_executable(ESMCI_FeatureUTest  ESMCI_FeatureUTest.C ESMF_FeatureTR15581Subr.F90 ESMCI_FeatureSubr.C)
target_link_libraries(ESMCI_FeatureUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMCI_FeatureUTest OpenMP::OpenMP_Fortran)
target_link_libraries(ESMCI_FeatureUTest OpenMP::OpenMP_CXX)
endif()
add_test(RUN_ESMF_StringUTest COMMAND ESMF_StringUTest)
set_property(TEST RUN_ESMF_StringUTest PROPERTY LABEL MPI )
add_test(RUN_ESMF_WordsizeUTest COMMAND ESMF_WordsizeUTest)
set_property(TEST RUN_ESMF_WordsizeUTest PROPERTY LABEL MPI )
add_test(RUN_ESMF_F90ArrayPtrUTest COMMAND ESMF_F90ArrayPtrUTest)
set_property(TEST RUN_ESMF_F90ArrayPtrUTest PROPERTY LABEL MPI )
add_test(RUN_ESMF_LAPACKUTest COMMAND ESMF_LAPACKUTest)
set_property(TEST RUN_ESMF_LAPACKUTest PROPERTY LABEL MPI )
add_test(RUN_ESMF_FeatureUTest COMMAND ESMF_FeatureUTest)
set_property(TEST RUN_ESMF_FeatureUTest PROPERTY LABEL MPI )
add_test(RUN_ESMF_ExceptionsUTest COMMAND ESMF_ExceptionsUTest)
set_property(TEST RUN_ESMF_ExceptionsUTest PROPERTY LABEL MPI )
add_test(RUN_ESMCI_ExceptionsUTest COMMAND ESMCI_ExceptionsUTest)
set_property(TEST RUN_ESMCI_ExceptionsUTest PROPERTY LABEL MPI )
add_test(RUN_ESMCI_FeatureUTest COMMAND ESMCI_FeatureUTest)
set_property(TEST RUN_ESMCI_FeatureUTest PROPERTY LABEL MPI )
add_test(RUN_ESMF_StringUTestUNI COMMAND ESMF_StringUTest)
set_property(TEST RUN_ESMF_StringUTestUNI PROPERTY LABEL serial )
add_test(RUN_ESMF_WordsizeUTestUNI COMMAND ESMF_WordsizeUTest)
set_property(TEST RUN_ESMF_WordsizeUTestUNI PROPERTY LABEL serial )
add_test(RUN_ESMF_F90ArrayPtrUTestUNI COMMAND ESMF_F90ArrayPtrUTest)
set_property(TEST RUN_ESMF_F90ArrayPtrUTestUNI PROPERTY LABEL serial )
add_test(RUN_ESMF_LAPACKUTestUNI COMMAND ESMF_LAPACKUTest)
set_property(TEST RUN_ESMF_LAPACKUTestUNI PROPERTY LABEL serial )
add_test(RUN_ESMF_FeatureUTestUNI COMMAND ESMF_FeatureUTest)
set_property(TEST RUN_ESMF_FeatureUTestUNI PROPERTY LABEL serial )
add_test(RUN_ESMF_ExceptionsUTestUNI COMMAND ESMF_ExceptionsUTest)
set_property(TEST RUN_ESMF_ExceptionsUTestUNI PROPERTY LABEL serial )
add_test(RUN_ESMCI_ExceptionsUTestUNI COMMAND ESMCI_ExceptionsUTest)
set_property(TEST RUN_ESMCI_ExceptionsUTestUNI PROPERTY LABEL serial )
add_test(RUN_ESMCI_FeatureUTestUNI COMMAND ESMCI_FeatureUTest)
set_property(TEST RUN_ESMCI_FeatureUTestUNI PROPERTY LABEL serial )
