
target_include_directories(esmf PRIVATE ${ESMF_SOURCE_DIR}/src/Infrastructure/IO/tests/../include)

if(${Git_FOUND})
    string(REGEX REPLACE "^([0-9]+)\.([0-9]+)(\.[0-9]+)?$" "\\1.\\2" ESMF_VERSION_STRING_GIT ${GIT_VERSION_STRING})
    add_compile_definitions(ESMF_VERSION_STRING_GIT="${ESMF_VERSION_STRING_GIT}")
endif()
add_executable(ESMCI_IO_NetCDF_UtilsUTest  ESMCI_IO_NetCDF_UtilsUTest.C)
target_link_libraries(ESMCI_IO_NetCDF_UtilsUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMCI_IO_NetCDF_UtilsUTest OpenMP::OpenMP_CXX)
endif()
add_executable(ESMCI_IO_NetCDFUTest  ESMCI_IO_NetCDFUTest.C)
target_link_libraries(ESMCI_IO_NetCDFUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMCI_IO_NetCDFUTest OpenMP::OpenMP_CXX)
endif()
add_executable(ESMCI_IO_PIOUTest  ESMCI_IO_PIOUTest.C)
target_link_libraries(ESMCI_IO_PIOUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMCI_IO_PIOUTest OpenMP::OpenMP_CXX)
endif()
add_executable(ESMC_IO_InqUTest  ESMC_IO_InqUTest.c)
target_link_libraries(ESMC_IO_InqUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMC_IO_InqUTest OpenMP::OpenMP_C)
endif()
add_executable(ESMF_IO_YAMLUTest  ESMF_IO_YAMLUTest.F90)
target_link_libraries(ESMF_IO_YAMLUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMF_IO_YAMLUTest OpenMP::OpenMP_Fortran)
endif()
add_executable(ESMF_IOUTest  ESMF_IOUTest.F90)
target_link_libraries(ESMF_IOUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMF_IOUTest OpenMP::OpenMP_Fortran)
endif()
add_executable(ESMF_IO_MultitileUTest  ESMF_IO_MultitileUTest.F90)
target_link_libraries(ESMF_IO_MultitileUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMF_IO_MultitileUTest OpenMP::OpenMP_Fortran)
endif()
add_executable(ESMF_IO_FileTypeCheckUTest  ESMF_IO_FileTypeCheckUTest.F90)
target_link_libraries(ESMF_IO_FileTypeCheckUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMF_IO_FileTypeCheckUTest OpenMP::OpenMP_Fortran)
endif()
add_test(RUN_ESMCI_IO_NetCDF_UtilsUTest COMMAND ESMCI_IO_NetCDF_UtilsUTest)
set_property(TEST RUN_ESMCI_IO_NetCDF_UtilsUTest PROPERTY LABEL MPI )
add_test(RUN_ESMCI_IO_NetCDFUTest COMMAND ESMCI_IO_NetCDFUTest)
set_property(TEST RUN_ESMCI_IO_NetCDFUTest PROPERTY LABEL MPI )
add_test(RUN_ESMCI_IO_PIOUTest COMMAND ESMCI_IO_PIOUTest)
set_property(TEST RUN_ESMCI_IO_PIOUTest PROPERTY LABEL MPI )
add_test(RUN_ESMC_IO_InqUTest COMMAND ESMC_IO_InqUTest)
set_property(TEST RUN_ESMC_IO_InqUTest PROPERTY LABEL MPI )
add_test(RUN_ESMF_IO_YAMLUTest COMMAND ESMF_IO_YAMLUTest)
set_property(TEST RUN_ESMF_IO_YAMLUTest PROPERTY LABEL MPI )
add_test(RUN_ESMF_IOUTest COMMAND ESMF_IOUTest)
set_property(TEST RUN_ESMF_IOUTest PROPERTY LABEL MPI )
add_test(RUN_ESMF_IO_MultitileUTest COMMAND ESMF_IO_MultitileUTest)
set_property(TEST RUN_ESMF_IO_MultitileUTest PROPERTY LABEL MPI )
add_test(RUN_ESMF_IO_FileTypeCheckUTest COMMAND ESMF_IO_FileTypeCheckUTest)
set_property(TEST RUN_ESMF_IO_FileTypeCheckUTest PROPERTY LABEL MPI )
add_test(RUN_ESMCI_IO_NetCDF_UtilsUTestUNI COMMAND ESMCI_IO_NetCDF_UtilsUTest)
set_property(TEST RUN_ESMCI_IO_NetCDF_UtilsUTestUNI PROPERTY LABEL serial )
add_test(RUN_ESMCI_IO_NetCDFUTestUNI COMMAND ESMCI_IO_NetCDFUTest)
set_property(TEST RUN_ESMCI_IO_NetCDFUTestUNI PROPERTY LABEL serial )
add_test(RUN_ESMCI_IO_PIOUTestUNI COMMAND ESMCI_IO_PIOUTest)
set_property(TEST RUN_ESMCI_IO_PIOUTestUNI PROPERTY LABEL serial )
add_test(RUN_ESMC_IO_InqUTestUNI COMMAND ESMC_IO_InqUTest)
set_property(TEST RUN_ESMC_IO_InqUTestUNI PROPERTY LABEL serial )
add_test(RUN_ESMF_IO_YAMLUTestUNI COMMAND ESMF_IO_YAMLUTest)
set_property(TEST RUN_ESMF_IO_YAMLUTestUNI PROPERTY LABEL serial )
add_test(RUN_ESMF_IOUTestUNI COMMAND ESMF_IOUTest)
set_property(TEST RUN_ESMF_IOUTestUNI PROPERTY LABEL serial )
add_test(RUN_ESMF_IO_FileTypeCheckUTestUNI COMMAND ESMF_IO_FileTypeCheckUTest)
set_property(TEST RUN_ESMF_IO_FileTypeCheckUTestUNI PROPERTY LABEL serial )
