
if(${Git_FOUND})
    string(REGEX REPLACE "^([0-9]+)\.([0-9]+)(\.[0-9]+)?$" "\\1.\\2" ESMF_VERSION_STRING_GIT ${GIT_VERSION_STRING})
    add_compile_definitions(ESMF_VERSION_STRING_GIT="${ESMF_VERSION_STRING_GIT}")
endif()
add_executable(ESMF_IOCompUTest  ESMF_IOCompUTest.F90)
target_link_libraries(ESMF_IOCompUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMF_IOCompUTest OpenMP::OpenMP_Fortran)
endif()
add_test(RUN_ESMF_IOCompUTest COMMAND ESMF_IOCompUTest)
set_property(TEST RUN_ESMF_IOCompUTest PROPERTY LABEL MPI )
add_test(RUN_ESMF_IOCompUTestUNI COMMAND ESMF_IOCompUTest)
set_property(TEST RUN_ESMF_IOCompUTestUNI PROPERTY LABEL serial )
