
target_include_directories(esmf PRIVATE ${ESMF_SOURCE_DIR}/src/Infrastructure/LogErr/tests/../include)

if(${Git_FOUND})
    string(REGEX REPLACE "^([0-9]+)\.([0-9]+)(\.[0-9]+)?$" "\\1.\\2" ESMF_VERSION_STRING_GIT ${GIT_VERSION_STRING})
    add_compile_definitions(ESMF_VERSION_STRING_GIT="${ESMF_VERSION_STRING_GIT}")
endif()
add_executable(ESMC_LogErrUTest  ESMCI_TestError.C ESMC_LogErrUTest.c)
target_link_libraries(ESMC_LogErrUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMC_LogErrUTest OpenMP::OpenMP_CXX)
target_link_libraries(ESMC_LogErrUTest OpenMP::OpenMP_C)
endif()
add_executable(ESMCI_LogErrPerfUTest  ESMCI_LogErrPerfUTest.C)
target_link_libraries(ESMCI_LogErrPerfUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMCI_LogErrPerfUTest OpenMP::OpenMP_CXX)
endif()
add_executable(ESMF_LogErrUTest  ESMCI_TestError.C ESMF_LogErrUTest.F90)
target_link_libraries(ESMF_LogErrUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMF_LogErrUTest OpenMP::OpenMP_Fortran)
target_link_libraries(ESMF_LogErrUTest OpenMP::OpenMP_CXX)
endif()
add_executable(ESMF_LogErrPerfUTest  ESMF_LogErrPerfUTest.F90)
target_link_libraries(ESMF_LogErrPerfUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMF_LogErrPerfUTest OpenMP::OpenMP_Fortran)
endif()
add_test(RUN_ESMC_LogErrUTest COMMAND ESMC_LogErrUTest)
set_property(TEST RUN_ESMC_LogErrUTest PROPERTY LABEL MPI )
add_test(RUN_ESMCI_LogErrPerfUTest COMMAND ESMCI_LogErrPerfUTest)
set_property(TEST RUN_ESMCI_LogErrPerfUTest PROPERTY LABEL MPI )
add_test(RUN_ESMF_LogErrUTest COMMAND ESMF_LogErrUTest)
set_property(TEST RUN_ESMF_LogErrUTest PROPERTY LABEL MPI )
add_test(RUN_ESMF_LogErrPerfUTest COMMAND ESMF_LogErrPerfUTest)
set_property(TEST RUN_ESMF_LogErrPerfUTest PROPERTY LABEL MPI )
add_test(RUN_ESMC_LogErrUTestUNI COMMAND ESMC_LogErrUTest)
set_property(TEST RUN_ESMC_LogErrUTestUNI PROPERTY LABEL serial )
add_test(RUN_ESMCI_LogErrPerfUTestUNI COMMAND ESMCI_LogErrPerfUTest)
set_property(TEST RUN_ESMCI_LogErrPerfUTestUNI PROPERTY LABEL serial )
add_test(RUN_ESMF_LogErrUTestUNI COMMAND ESMF_LogErrUTest)
set_property(TEST RUN_ESMF_LogErrUTestUNI PROPERTY LABEL serial )
add_test(RUN_ESMF_LogErrPerfUTestUNI COMMAND ESMF_LogErrPerfUTest)
set_property(TEST RUN_ESMF_LogErrPerfUTestUNI PROPERTY LABEL serial )
