
target_include_directories(esmf PRIVATE ${ESMF_SOURCE_DIR}/src/Infrastructure/DELayout/tests/../include)

if(${Git_FOUND})
    string(REGEX REPLACE "^([0-9]+)\.([0-9]+)(\.[0-9]+)?$" "\\1.\\2" ESMF_VERSION_STRING_GIT ${GIT_VERSION_STRING})
    add_compile_definitions(ESMF_VERSION_STRING_GIT="${ESMF_VERSION_STRING_GIT}")
endif()
add_executable(ESMF_DELayoutUTest  ESMF_DELayoutUTest.F90)
target_link_libraries(ESMF_DELayoutUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMF_DELayoutUTest OpenMP::OpenMP_Fortran)
endif()
add_executable(ESMF_DELayoutWorkQueueUTest  ESMF_DELayoutWorkQueueUTest.F90)
target_link_libraries(ESMF_DELayoutWorkQueueUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMF_DELayoutWorkQueueUTest OpenMP::OpenMP_Fortran)
endif()
add_test(RUN_ESMF_DELayoutUTest COMMAND ESMF_DELayoutUTest)
set_property(TEST RUN_ESMF_DELayoutUTest PROPERTY LABEL MPI )
add_test(RUN_ESMF_DELayoutWorkQueueUTest COMMAND ESMF_DELayoutWorkQueueUTest)
set_property(TEST RUN_ESMF_DELayoutWorkQueueUTest PROPERTY LABEL MPI )
add_test(RUN_ESMF_DELayoutUTestUNI COMMAND ESMF_DELayoutUTest)
set_property(TEST RUN_ESMF_DELayoutUTestUNI PROPERTY LABEL serial )
add_test(RUN_ESMF_DELayoutWorkQueueUTestUNI COMMAND ESMF_DELayoutWorkQueueUTest)
set_property(TEST RUN_ESMF_DELayoutWorkQueueUTestUNI PROPERTY LABEL serial )
