
target_include_directories(esmf PRIVATE ${ESMF_SOURCE_DIR}/src/epilogue/tests/../include)

if(${Git_FOUND})
    string(REGEX REPLACE "^([0-9]+)\.([0-9]+)(\.[0-9]+)?$" "\\1.\\2" ESMF_VERSION_STRING_GIT ${GIT_VERSION_STRING})
    add_compile_definitions(ESMF_VERSION_STRING_GIT="${ESMF_VERSION_STRING_GIT}")
endif()
add_executable(ESMF_TestUTest  ESMF_TestUTest.F90)
target_link_libraries(ESMF_TestUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMF_TestUTest OpenMP::OpenMP_Fortran)
endif()
add_executable(ESMCI_TestUTest  ESMCI_TestUTest.C)
target_link_libraries(ESMCI_TestUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMCI_TestUTest OpenMP::OpenMP_CXX)
endif()
add_executable(ESMC_TestUTest  ESMC_TestUTest.c)
target_link_libraries(ESMC_TestUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMC_TestUTest OpenMP::OpenMP_C)
endif()
add_test(RUN_ESMF_TestUTest COMMAND ESMF_TestUTest)
set_property(TEST RUN_ESMF_TestUTest PROPERTY LABEL MPI )
add_test(RUN_ESMCI_TestUTest COMMAND ESMCI_TestUTest)
set_property(TEST RUN_ESMCI_TestUTest PROPERTY LABEL MPI )
add_test(RUN_ESMC_TestUTest COMMAND ESMC_TestUTest)
set_property(TEST RUN_ESMC_TestUTest PROPERTY LABEL MPI )
add_test(RUN_ESMF_TestUTestUNI COMMAND ESMF_TestUTest)
set_property(TEST RUN_ESMF_TestUTestUNI PROPERTY LABEL serial )
add_test(RUN_ESMCI_TestUTestUNI COMMAND ESMCI_TestUTest)
set_property(TEST RUN_ESMCI_TestUTestUNI PROPERTY LABEL serial )
add_test(RUN_ESMC_TestUTestUNI COMMAND ESMC_TestUTest)
set_property(TEST RUN_ESMC_TestUTestUNI PROPERTY LABEL serial )
