
if(${Git_FOUND})
    string(REGEX REPLACE "^([0-9]+)\.([0-9]+)(\.[0-9]+)?$" "\\1.\\2" ESMF_VERSION_STRING_GIT ${GIT_VERSION_STRING})
    add_compile_definitions(ESMF_VERSION_STRING_GIT="${ESMF_VERSION_STRING_GIT}")
endif()
add_executable(ESMF_TestHarnessUTest  ESMF_TestHarnessParser.F90 ESMF_TestHarnessGridMod.F90 ESMF_TestHarnessDistMod.F90 ESMF_TestHarnessMod.F90 ESMF_TestHarnessReportMod.F90 ESMF_TestHarnessUTest.F90 ESMF_TestHarnessTypesMod.F90 ESMF_TestHarnessUtilMod.F90)
target_link_libraries(ESMF_TestHarnessUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMF_TestHarnessUTest OpenMP::OpenMP_Fortran)
endif()
add_executable(ESMCI_TestHarnessLatexPPUTest  ESMCI_TestHarnessLatexPPUTest.C)
target_link_libraries(ESMCI_TestHarnessLatexPPUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMCI_TestHarnessLatexPPUTest OpenMP::OpenMP_CXX)
endif()
