
target_include_directories(esmf PRIVATE ${ESMF_SOURCE_DIR}/src/Superstructure/Mapper/tests/../include)

if(${Git_FOUND})
    string(REGEX REPLACE "^([0-9]+)\.([0-9]+)(\.[0-9]+)?$" "\\1.\\2" ESMF_VERSION_STRING_GIT ${GIT_VERSION_STRING})
    add_compile_definitions(ESMF_VERSION_STRING_GIT="${ESMF_VERSION_STRING_GIT}")
endif()
add_executable(ESMCI_PolyUTest  ESMCI_PolyUTest.C)
target_link_libraries(ESMCI_PolyUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMCI_PolyUTest OpenMP::OpenMP_CXX)
endif()
add_executable(ESMCI_TwoVPolyUTest  ESMCI_TwoVPolyUTest.C)
target_link_libraries(ESMCI_TwoVPolyUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMCI_TwoVPolyUTest OpenMP::OpenMP_CXX)
endif()
add_executable(ESMCI_TwoDVPolyUTest  ESMCI_TwoDVPolyUTest.C)
target_link_libraries(ESMCI_TwoDVPolyUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMCI_TwoDVPolyUTest OpenMP::OpenMP_CXX)
endif()
add_executable(ESMCI_MVLPolyUTest  ESMCI_MVLPolyUTest.C)
target_link_libraries(ESMCI_MVLPolyUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMCI_MVLPolyUTest OpenMP::OpenMP_CXX)
endif()
add_executable(ESMCI_MatUTest  ESMCI_MatUTest.C)
target_link_libraries(ESMCI_MatUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMCI_MatUTest OpenMP::OpenMP_CXX)
endif()
add_executable(ESMCI_PolyFitUTest  ESMCI_PolyFitUTest.C)
target_link_libraries(ESMCI_PolyFitUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMCI_PolyFitUTest OpenMP::OpenMP_CXX)
endif()
add_executable(ESMCI_LFitUTest  ESMCI_LFitUTest.C)
target_link_libraries(ESMCI_LFitUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMCI_LFitUTest OpenMP::OpenMP_CXX)
endif()
add_executable(ESMCI_SolverUTest  ESMCI_SolverUTest.C)
target_link_libraries(ESMCI_SolverUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMCI_SolverUTest OpenMP::OpenMP_CXX)
endif()
add_executable(ESMCI_GraphUTest  ESMCI_GraphUTest.C)
target_link_libraries(ESMCI_GraphUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMCI_GraphUTest OpenMP::OpenMP_CXX)
endif()
add_executable(ESMCI_RunSeqUTest  ESMCI_RunSeqUTest.C)
target_link_libraries(ESMCI_RunSeqUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMCI_RunSeqUTest OpenMP::OpenMP_CXX)
endif()
add_executable(ESMCI_ExecBlockUTest  ESMCI_ExecBlockUTest.C)
target_link_libraries(ESMCI_ExecBlockUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMCI_ExecBlockUTest OpenMP::OpenMP_CXX)
endif()
add_executable(ESMCI_CompInfoUTest  ESMCI_CompInfoUTest.C)
target_link_libraries(ESMCI_CompInfoUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMCI_CompInfoUTest OpenMP::OpenMP_CXX)
endif()
add_executable(ESMCI_LoadBalancerUTest  ESMCI_LoadBalancerUTest.C)
target_link_libraries(ESMCI_LoadBalancerUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMCI_LoadBalancerUTest OpenMP::OpenMP_CXX)
endif()
add_executable(ESMCI_MapperUTest  ESMCI_MapperUTest.C)
target_link_libraries(ESMCI_MapperUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMCI_MapperUTest OpenMP::OpenMP_CXX)
endif()
add_executable(ESMCI_MapperMCompsUTest  ESMCI_MapperMCompsUTest.C)
target_link_libraries(ESMCI_MapperMCompsUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMCI_MapperMCompsUTest OpenMP::OpenMP_CXX)
endif()
add_executable(ESMCI_MapperMComps2UTest  ESMCI_MapperMComps2UTest.C)
target_link_libraries(ESMCI_MapperMComps2UTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMCI_MapperMComps2UTest OpenMP::OpenMP_CXX)
endif()
add_executable(ESMCI_MapperMCompsDepUTest  ESMCI_MapperMCompsDepUTest.C)
target_link_libraries(ESMCI_MapperMCompsDepUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMCI_MapperMCompsDepUTest OpenMP::OpenMP_CXX)
endif()
add_executable(ESMCI_LoadBalancerMCompsUTest  ESMCI_LoadBalancerMCompsUTest.C)
target_link_libraries(ESMCI_LoadBalancerMCompsUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMCI_LoadBalancerMCompsUTest OpenMP::OpenMP_CXX)
endif()
add_test(RUN_ESMCI_PolyUTestUNI COMMAND ESMCI_PolyUTest)
set_property(TEST RUN_ESMCI_PolyUTestUNI PROPERTY LABEL serial )
add_test(RUN_ESMCI_TwoVPolyUTestUNI COMMAND ESMCI_TwoVPolyUTest)
set_property(TEST RUN_ESMCI_TwoVPolyUTestUNI PROPERTY LABEL serial )
add_test(RUN_ESMCI_TwoDVPolyUTestUNI COMMAND ESMCI_TwoDVPolyUTest)
set_property(TEST RUN_ESMCI_TwoDVPolyUTestUNI PROPERTY LABEL serial )
add_test(RUN_ESMCI_MVLPolyUTestUNI COMMAND ESMCI_MVLPolyUTest)
set_property(TEST RUN_ESMCI_MVLPolyUTestUNI PROPERTY LABEL serial )
add_test(RUN_ESMCI_MatUTestUNI COMMAND ESMCI_MatUTest)
set_property(TEST RUN_ESMCI_MatUTestUNI PROPERTY LABEL serial )
add_test(RUN_ESMCI_PolyFitUTestUNI COMMAND ESMCI_PolyFitUTest)
set_property(TEST RUN_ESMCI_PolyFitUTestUNI PROPERTY LABEL serial )
add_test(RUN_ESMCI_LFitUTestUNI COMMAND ESMCI_LFitUTest)
set_property(TEST RUN_ESMCI_LFitUTestUNI PROPERTY LABEL serial )
add_test(RUN_ESMCI_SolverUTestUNI COMMAND ESMCI_SolverUTest)
set_property(TEST RUN_ESMCI_SolverUTestUNI PROPERTY LABEL serial )
add_test(RUN_ESMCI_GraphUTestUNI COMMAND ESMCI_GraphUTest)
set_property(TEST RUN_ESMCI_GraphUTestUNI PROPERTY LABEL serial )
add_test(RUN_ESMCI_RunSeqUTestUNI COMMAND ESMCI_RunSeqUTest)
set_property(TEST RUN_ESMCI_RunSeqUTestUNI PROPERTY LABEL serial )
add_test(RUN_ESMCI_ExecBlockUTestUNI COMMAND ESMCI_ExecBlockUTest)
set_property(TEST RUN_ESMCI_ExecBlockUTestUNI PROPERTY LABEL serial )
add_test(RUN_ESMCI_CompInfoUTestUNI COMMAND ESMCI_CompInfoUTest)
set_property(TEST RUN_ESMCI_CompInfoUTestUNI PROPERTY LABEL serial )
add_test(RUN_ESMCI_LoadBalancerUTestUNI COMMAND ESMCI_LoadBalancerUTest)
set_property(TEST RUN_ESMCI_LoadBalancerUTestUNI PROPERTY LABEL serial )
add_test(RUN_ESMCI_MapperUTestUNI COMMAND ESMCI_MapperUTest)
set_property(TEST RUN_ESMCI_MapperUTestUNI PROPERTY LABEL serial )
add_test(RUN_ESMCI_MapperMCompsUTestUNI COMMAND ESMCI_MapperMCompsUTest)
set_property(TEST RUN_ESMCI_MapperMCompsUTestUNI PROPERTY LABEL serial )
add_test(RUN_ESMCI_MapperMComps2UTestUNI COMMAND ESMCI_MapperMComps2UTest)
set_property(TEST RUN_ESMCI_MapperMComps2UTestUNI PROPERTY LABEL serial )
add_test(RUN_ESMCI_MapperMCompsDepUTestUNI COMMAND ESMCI_MapperMCompsDepUTest)
set_property(TEST RUN_ESMCI_MapperMCompsDepUTestUNI PROPERTY LABEL serial )
add_test(RUN_ESMCI_LoadBalancerMCompsUTestUNI COMMAND ESMCI_LoadBalancerMCompsUTest)
set_property(TEST RUN_ESMCI_LoadBalancerMCompsUTestUNI PROPERTY LABEL serial )
