
target_include_directories(esmf PRIVATE ${ESMF_SOURCE_DIR}/src/Superstructure/Component/tests/../include)

if(${Git_FOUND})
    string(REGEX REPLACE "^([0-9]+)\.([0-9]+)(\.[0-9]+)?$" "\\1.\\2" ESMF_VERSION_STRING_GIT ${GIT_VERSION_STRING})
    add_compile_definitions(ESMF_VERSION_STRING_GIT="${ESMF_VERSION_STRING_GIT}")
endif()
add_executable(ESMF_ComponentUTest  ESMF_ComponentUTest.F90)
target_link_libraries(ESMF_ComponentUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMF_ComponentUTest OpenMP::OpenMP_Fortran)
endif()
add_executable(ESMF_GridCompCreateUTest  ESMF_GridCompCreateUTest.F90)
target_link_libraries(ESMF_GridCompCreateUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMF_GridCompCreateUTest OpenMP::OpenMP_Fortran)
endif()
add_executable(ESMF_CplCompCreateUTest  ESMF_CplCompCreateUTest.F90)
target_link_libraries(ESMF_CplCompCreateUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMF_CplCompCreateUTest OpenMP::OpenMP_Fortran)
endif()
add_executable(ESMF_SciCompCreateUTest  ESMF_SciCompCreateUTest.F90)
target_link_libraries(ESMF_SciCompCreateUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMF_SciCompCreateUTest OpenMP::OpenMP_Fortran)
endif()
add_executable(ESMF_CompSetServUTest  ESMF_CompSetServUTest.F90 ESMF_SetServCode.F90)
target_link_libraries(ESMF_CompSetServUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMF_CompSetServUTest OpenMP::OpenMP_Fortran)
endif()
add_executable(ESMF_StdCompMethodsUTest  ESMF_StdCompMethodsUTest.F90)
target_link_libraries(ESMF_StdCompMethodsUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMF_StdCompMethodsUTest OpenMP::OpenMP_Fortran)
endif()
add_executable(ESMF_CompTunnelUTest  ESMF_CompTunnelUTest.F90)
target_link_libraries(ESMF_CompTunnelUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMF_CompTunnelUTest OpenMP::OpenMP_Fortran)
endif()
add_executable(ESMC_ComponentUTest  ESMC_ComponentUTest.c)
target_link_libraries(ESMC_ComponentUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMC_ComponentUTest OpenMP::OpenMP_C)
endif()
add_test(RUN_ESMF_ComponentUTest COMMAND ESMF_ComponentUTest)
set_property(TEST RUN_ESMF_ComponentUTest PROPERTY LABEL MPI )
add_test(RUN_ESMF_GridCompCreateUTest COMMAND ESMF_GridCompCreateUTest)
set_property(TEST RUN_ESMF_GridCompCreateUTest PROPERTY LABEL MPI )
add_test(RUN_ESMF_CplCompCreateUTest COMMAND ESMF_CplCompCreateUTest)
set_property(TEST RUN_ESMF_CplCompCreateUTest PROPERTY LABEL MPI )
add_test(RUN_ESMF_SciCompCreateUTest COMMAND ESMF_SciCompCreateUTest)
set_property(TEST RUN_ESMF_SciCompCreateUTest PROPERTY LABEL MPI )
add_test(RUN_ESMF_CompSetServUTest COMMAND ESMF_CompSetServUTest)
set_property(TEST RUN_ESMF_CompSetServUTest PROPERTY LABEL MPI )
add_test(RUN_ESMF_StdCompMethodsUTest COMMAND ESMF_StdCompMethodsUTest)
set_property(TEST RUN_ESMF_StdCompMethodsUTest PROPERTY LABEL MPI )
add_test(RUN_ESMF_CompTunnelUTest COMMAND ESMF_CompTunnelUTest)
set_property(TEST RUN_ESMF_CompTunnelUTest PROPERTY LABEL MPI )
add_test(RUN_ESMC_ComponentUTest COMMAND ESMC_ComponentUTest)
set_property(TEST RUN_ESMC_ComponentUTest PROPERTY LABEL MPI )
add_test(RUN_ESMF_ComponentUTestUNI COMMAND ESMF_ComponentUTest)
set_property(TEST RUN_ESMF_ComponentUTestUNI PROPERTY LABEL serial )
add_test(RUN_ESMF_GridCompCreateUTestUNI COMMAND ESMF_GridCompCreateUTest)
set_property(TEST RUN_ESMF_GridCompCreateUTestUNI PROPERTY LABEL serial )
add_test(RUN_ESMF_CplCompCreateUTestUNI COMMAND ESMF_CplCompCreateUTest)
set_property(TEST RUN_ESMF_CplCompCreateUTestUNI PROPERTY LABEL serial )
add_test(RUN_ESMF_SciCompCreateUTestUNI COMMAND ESMF_SciCompCreateUTest)
set_property(TEST RUN_ESMF_SciCompCreateUTestUNI PROPERTY LABEL serial )
add_test(RUN_ESMF_CompSetServUTestUNI COMMAND ESMF_CompSetServUTest)
set_property(TEST RUN_ESMF_CompSetServUTestUNI PROPERTY LABEL serial )
add_test(RUN_ESMF_StdCompMethodsUTestUNI COMMAND ESMF_StdCompMethodsUTest)
set_property(TEST RUN_ESMF_StdCompMethodsUTestUNI PROPERTY LABEL serial )
add_test(RUN_ESMC_ComponentUTestUNI COMMAND ESMC_ComponentUTest)
set_property(TEST RUN_ESMC_ComponentUTestUNI PROPERTY LABEL serial )
