
target_include_directories(esmf PRIVATE ${ESMF_SOURCE_DIR}/src/Infrastructure/Grid/tests/../include)

if(${Git_FOUND})
    string(REGEX REPLACE "^([0-9]+)\.([0-9]+)(\.[0-9]+)?$" "\\1.\\2" ESMF_VERSION_STRING_GIT ${GIT_VERSION_STRING})
    add_compile_definitions(ESMF_VERSION_STRING_GIT="${ESMF_VERSION_STRING_GIT}")
endif()
add_executable(ESMC_GridUTest  ESMC_GridUTest.c)
target_link_libraries(ESMC_GridUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMC_GridUTest OpenMP::OpenMP_C)
endif()
add_executable(ESMF_GridCreateUTest  ESMF_GridCreateUTest.F90)
target_link_libraries(ESMF_GridCreateUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMF_GridCreateUTest OpenMP::OpenMP_Fortran)
endif()
add_executable(ESMF_GridCoordUTest  ESMF_GridCoordUTest.F90)
target_link_libraries(ESMF_GridCoordUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMF_GridCoordUTest OpenMP::OpenMP_Fortran)
endif()
add_executable(ESMF_GridItemUTest  ESMF_GridItemUTest.F90)
target_link_libraries(ESMF_GridItemUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMF_GridItemUTest OpenMP::OpenMP_Fortran)
endif()
add_executable(ESMF_GridArbitraryUTest  ESMF_GridArbitraryUTest.F90)
target_link_libraries(ESMF_GridArbitraryUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMF_GridArbitraryUTest OpenMP::OpenMP_Fortran)
endif()
add_test(RUN_ESMC_GridUTest COMMAND ESMC_GridUTest)
set_property(TEST RUN_ESMC_GridUTest PROPERTY LABEL MPI )
add_test(RUN_ESMF_GridCreateUTest COMMAND ESMF_GridCreateUTest)
set_property(TEST RUN_ESMF_GridCreateUTest PROPERTY LABEL MPI )
add_test(RUN_ESMF_GridCoordUTest COMMAND ESMF_GridCoordUTest)
set_property(TEST RUN_ESMF_GridCoordUTest PROPERTY LABEL MPI )
add_test(RUN_ESMF_GridItemUTest COMMAND ESMF_GridItemUTest)
set_property(TEST RUN_ESMF_GridItemUTest PROPERTY LABEL MPI )
add_test(RUN_ESMF_GridArbitraryUTest COMMAND ESMF_GridArbitraryUTest)
set_property(TEST RUN_ESMF_GridArbitraryUTest PROPERTY LABEL MPI )
add_test(RUN_ESMC_GridUTestUNI COMMAND ESMC_GridUTest)
set_property(TEST RUN_ESMC_GridUTestUNI PROPERTY LABEL serial )
add_test(RUN_ESMF_GridCreateUTestUNI COMMAND ESMF_GridCreateUTest)
set_property(TEST RUN_ESMF_GridCreateUTestUNI PROPERTY LABEL serial )
add_test(RUN_ESMF_GridCoordUTestUNI COMMAND ESMF_GridCoordUTest)
set_property(TEST RUN_ESMF_GridCoordUTestUNI PROPERTY LABEL serial )
add_test(RUN_ESMF_GridItemUTestUNI COMMAND ESMF_GridItemUTest)
set_property(TEST RUN_ESMF_GridItemUTestUNI PROPERTY LABEL serial )
add_test(RUN_ESMF_GridArbitraryUTestUNI COMMAND ESMF_GridArbitraryUTest)
set_property(TEST RUN_ESMF_GridArbitraryUTestUNI PROPERTY LABEL serial )
