
target_include_directories(esmf PRIVATE ${ESMF_SOURCE_DIR}/src/Infrastructure/Mesh/tests/../include)

if(${Git_FOUND})
    string(REGEX REPLACE "^([0-9]+)\.([0-9]+)(\.[0-9]+)?$" "\\1.\\2" ESMF_VERSION_STRING_GIT ${GIT_VERSION_STRING})
    add_compile_definitions(ESMF_VERSION_STRING_GIT="${ESMF_VERSION_STRING_GIT}")
endif()
target_include_directories(esmf PRIVATE ${ESMF_SOURCE_DIR}/src/Infrastructure/Mesh/tests/../include ${ESMF_SOURCE_DIR}/src/Infrastructure/Mesh/tests/../include/Legacy ${ESMF_SOURCE_DIR}/src/Infrastructure/Mesh/tests/../include/Regridding ${ESMF_SOURCE_DIR}/src/Infrastructure/Mesh/tests/../src/Moab ${ESMF_SOURCE_DIR}/src/Infrastructure/Mesh/tests/../src/Moab/parallel ${ESMF_SOURCE_DIR}/src/Infrastructure/Mesh/tests/../src/Moab/LocalDiscretization)
add_executable(ESMCI_MBMesh_ExtrapolateUTest  ESMCI_MBMesh_ExtrapolateUTest.C)
target_link_libraries(ESMCI_MBMesh_ExtrapolateUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMCI_MBMesh_ExtrapolateUTest OpenMP::OpenMP_CXX)
endif()
add_executable(ESMCI_MBMesh_UtilUTest  ESMCI_MBMesh_UtilUTest.C)
target_link_libraries(ESMCI_MBMesh_UtilUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMCI_MBMesh_UtilUTest OpenMP::OpenMP_CXX)
endif()
add_executable(ESMCI_MeshCapUTest  ESMCI_MeshCapUTest.C)
target_link_libraries(ESMCI_MeshCapUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMCI_MeshCapUTest OpenMP::OpenMP_CXX)
endif()
add_executable(ESMCI_MeshCapRegridUTest  ESMCI_MeshCapRegridUTest.C)
target_link_libraries(ESMCI_MeshCapRegridUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMCI_MeshCapRegridUTest OpenMP::OpenMP_CXX)
endif()
add_executable(ESMCI_MeshMOABUTest  ESMCI_MeshMOABUTest.C)
target_link_libraries(ESMCI_MeshMOABUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMCI_MeshMOABUTest OpenMP::OpenMP_CXX)
endif()
add_executable(ESMCI_IntegrateUTest  ESMCI_IntegrateUTest.C)
target_link_libraries(ESMCI_IntegrateUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMCI_IntegrateUTest OpenMP::OpenMP_CXX)
endif()
add_executable(ESMCI_MeshUTest  ESMCI_MeshUTest.C)
target_link_libraries(ESMCI_MeshUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMCI_MeshUTest OpenMP::OpenMP_CXX)
endif()
add_executable(ESMC_MeshUTest  ESMC_MeshUTest.c)
target_link_libraries(ESMC_MeshUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMC_MeshUTest OpenMP::OpenMP_C)
endif()
add_executable(ESMCI_DInfoUTest  ESMCI_DInfoUTest.C ESMCI_DInfoUTest.o)
target_link_libraries(ESMCI_DInfoUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMCI_DInfoUTest OpenMP::OpenMP_CXX)
endif()
add_executable(ESMC_MeshVTKUTest  ESMC_MeshVTKUTest.c)
target_link_libraries(ESMC_MeshVTKUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMC_MeshVTKUTest OpenMP::OpenMP_C)
endif()
add_executable(ESMF_MeshOpUTest  ESMF_MeshOpUTest.F90)
target_link_libraries(ESMF_MeshOpUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMF_MeshOpUTest OpenMP::OpenMP_Fortran)
endif()
add_executable(ESMF_MeshUTest  ESMF_MeshUTest.F90)
target_link_libraries(ESMF_MeshUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMF_MeshUTest OpenMP::OpenMP_Fortran)
endif()
add_executable(ESMCI_NearestUTest  ESMCI_NearestUTest.C)
target_link_libraries(ESMCI_NearestUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMCI_NearestUTest OpenMP::OpenMP_CXX)
endif()
add_executable(ESMF_MeshFileIOUTest  ESMF_MeshFileIOUTest.F90)
target_link_libraries(ESMF_MeshFileIOUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMF_MeshFileIOUTest OpenMP::OpenMP_Fortran)
endif()
add_executable(ESMCI_Proj4UTest  ESMCI_Proj4UTest.C)
target_link_libraries(ESMCI_Proj4UTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMCI_Proj4UTest OpenMP::OpenMP_CXX)
endif()
add_test(RUN_ESMCI_MBMesh_ExtrapolateUTest COMMAND ESMCI_MBMesh_ExtrapolateUTest)
set_property(TEST RUN_ESMCI_MBMesh_ExtrapolateUTest PROPERTY LABEL MPI )
add_test(RUN_ESMCI_MBMesh_UtilUTest COMMAND ESMCI_MBMesh_UtilUTest)
set_property(TEST RUN_ESMCI_MBMesh_UtilUTest PROPERTY LABEL MPI )
add_test(RUN_ESMCI_MeshCapUTest COMMAND ESMCI_MeshCapUTest)
set_property(TEST RUN_ESMCI_MeshCapUTest PROPERTY LABEL MPI )
add_test(RUN_ESMCI_MeshCapRegridUTest COMMAND ESMCI_MeshCapRegridUTest)
set_property(TEST RUN_ESMCI_MeshCapRegridUTest PROPERTY LABEL MPI )
add_test(RUN_ESMCI_MeshMOABUTest COMMAND ESMCI_MeshMOABUTest)
set_property(TEST RUN_ESMCI_MeshMOABUTest PROPERTY LABEL MPI )
add_test(RUN_ESMCI_IntegrateUTest COMMAND ESMCI_IntegrateUTest)
set_property(TEST RUN_ESMCI_IntegrateUTest PROPERTY LABEL MPI )
add_test(RUN_ESMCI_MeshUTest COMMAND ESMCI_MeshUTest)
set_property(TEST RUN_ESMCI_MeshUTest PROPERTY LABEL MPI )
add_test(RUN_ESMC_MeshUTest COMMAND ESMC_MeshUTest)
set_property(TEST RUN_ESMC_MeshUTest PROPERTY LABEL MPI )
add_test(RUN_ESMCI_DInfoUTest COMMAND ESMCI_DInfoUTest)
set_property(TEST RUN_ESMCI_DInfoUTest PROPERTY LABEL MPI )
add_test(RUN_ESMC_MeshVTKUTest COMMAND ESMC_MeshVTKUTest)
set_property(TEST RUN_ESMC_MeshVTKUTest PROPERTY LABEL MPI )
add_test(RUN_ESMF_MeshOpUTest COMMAND ESMF_MeshOpUTest)
set_property(TEST RUN_ESMF_MeshOpUTest PROPERTY LABEL MPI )
add_test(RUN_ESMF_MeshUTest COMMAND ESMF_MeshUTest)
set_property(TEST RUN_ESMF_MeshUTest PROPERTY LABEL MPI )
add_test(RUN_ESMF_MeshFileIOUTest COMMAND ESMF_MeshFileIOUTest)
set_property(TEST RUN_ESMF_MeshFileIOUTest PROPERTY LABEL MPI )
add_test(RUN_ESMCI_NearestUTest COMMAND ESMCI_NearestUTest)
set_property(TEST RUN_ESMCI_NearestUTest PROPERTY LABEL MPI )
add_test(RUN_ESMCI_Proj4UTest COMMAND ESMCI_Proj4UTest)
set_property(TEST RUN_ESMCI_Proj4UTest PROPERTY LABEL MPI )
add_test(RUN_ESMCI_MBMesh_UtilUTestUNI COMMAND ESMCI_MBMesh_UtilUTest)
set_property(TEST RUN_ESMCI_MBMesh_UtilUTestUNI PROPERTY LABEL serial )
add_test(RUN_ESMCI_MeshCapUTestUNI COMMAND ESMCI_MeshCapUTest)
set_property(TEST RUN_ESMCI_MeshCapUTestUNI PROPERTY LABEL serial )
add_test(RUN_ESMCI_MeshCapRegridUTestUNI COMMAND ESMCI_MeshCapRegridUTest)
set_property(TEST RUN_ESMCI_MeshCapRegridUTestUNI PROPERTY LABEL serial )
add_test(RUN_ESMCI_MeshMOABUTestUNI COMMAND ESMCI_MeshMOABUTest)
set_property(TEST RUN_ESMCI_MeshMOABUTestUNI PROPERTY LABEL serial )
add_test(RUN_ESMCI_IntegrateUTestUNI COMMAND ESMCI_IntegrateUTest)
set_property(TEST RUN_ESMCI_IntegrateUTestUNI PROPERTY LABEL serial )
add_test(RUN_ESMCI_MeshUTestUNI COMMAND ESMCI_MeshUTest)
set_property(TEST RUN_ESMCI_MeshUTestUNI PROPERTY LABEL serial )
add_test(RUN_ESMC_MeshUTestUNI COMMAND ESMC_MeshUTest)
set_property(TEST RUN_ESMC_MeshUTestUNI PROPERTY LABEL serial )
add_test(RUN_ESMCI_DInfoUTestUNI COMMAND ESMCI_DInfoUTest)
set_property(TEST RUN_ESMCI_DInfoUTestUNI PROPERTY LABEL serial )
add_test(RUN_ESMF_MeshOpUTestUNI COMMAND ESMF_MeshOpUTest)
set_property(TEST RUN_ESMF_MeshOpUTestUNI PROPERTY LABEL serial )
add_test(RUN_ESMF_MeshUTestUNI COMMAND ESMF_MeshUTest)
set_property(TEST RUN_ESMF_MeshUTestUNI PROPERTY LABEL serial )
add_test(RUN_ESMF_MeshFileIOUTestUNI COMMAND ESMF_MeshFileIOUTest)
set_property(TEST RUN_ESMF_MeshFileIOUTestUNI PROPERTY LABEL serial )
add_test(RUN_ESMCI_Proj4UTestUNI COMMAND ESMCI_Proj4UTest)
set_property(TEST RUN_ESMCI_Proj4UTestUNI PROPERTY LABEL serial )
