
target_include_directories(esmf PRIVATE ${ESMF_SOURCE_DIR}/src/Infrastructure/LocStream/tests/../include)

if(${Git_FOUND})
    string(REGEX REPLACE "^([0-9]+)\.([0-9]+)(\.[0-9]+)?$" "\\1.\\2" ESMF_VERSION_STRING_GIT ${GIT_VERSION_STRING})
    add_compile_definitions(ESMF_VERSION_STRING_GIT="${ESMF_VERSION_STRING_GIT}")
endif()
add_executable(ESMF_LocStreamUTest  ESMF_LocStreamUTest.F90)
target_link_libraries(ESMF_LocStreamUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMF_LocStreamUTest OpenMP::OpenMP_Fortran)
endif()
add_executable(ESMC_LocStreamUTest  ESMC_LocStreamUTest.c)
target_link_libraries(ESMC_LocStreamUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMC_LocStreamUTest OpenMP::OpenMP_C)
endif()
add_test(RUN_ESMF_LocStreamUTest COMMAND ESMF_LocStreamUTest)
set_property(TEST RUN_ESMF_LocStreamUTest PROPERTY LABEL MPI )
add_test(RUN_ESMC_LocStreamUTest COMMAND ESMC_LocStreamUTest)
set_property(TEST RUN_ESMC_LocStreamUTest PROPERTY LABEL MPI )
add_test(RUN_ESMF_LocStreamUTestUNI COMMAND ESMF_LocStreamUTest)
set_property(TEST RUN_ESMF_LocStreamUTestUNI PROPERTY LABEL serial )
add_test(RUN_ESMC_LocStreamUTestUNI COMMAND ESMC_LocStreamUTest)
set_property(TEST RUN_ESMC_LocStreamUTestUNI PROPERTY LABEL serial )
