
target_include_directories(esmf PRIVATE ${ESMF_SOURCE_DIR}/src/Infrastructure/Array/tests/../include)

if(${Git_FOUND})
    string(REGEX REPLACE "^([0-9]+)\.([0-9]+)(\.[0-9]+)?$" "\\1.\\2" ESMF_VERSION_STRING_GIT ${GIT_VERSION_STRING})
    add_compile_definitions(ESMF_VERSION_STRING_GIT="${ESMF_VERSION_STRING_GIT}")
endif()
add_executable(ESMF_ArrayCreateGetUTest  ESMF_ArrayCreateGetUTest.F90)
target_link_libraries(ESMF_ArrayCreateGetUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMF_ArrayCreateGetUTest OpenMP::OpenMP_Fortran)
endif()
add_executable(ESMF_ArrayDataUTest  ESMF_ArrayDataUTest.F90)
target_link_libraries(ESMF_ArrayDataUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMF_ArrayDataUTest OpenMP::OpenMP_Fortran)
endif()
add_executable(ESMF_ArrayScatterUTest  ESMF_ArrayScatterUTest.F90)
target_link_libraries(ESMF_ArrayScatterUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMF_ArrayScatterUTest OpenMP::OpenMP_Fortran)
endif()
add_executable(ESMF_ArrayGatherUTest  ESMF_ArrayGatherUTest.F90)
target_link_libraries(ESMF_ArrayGatherUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMF_ArrayGatherUTest OpenMP::OpenMP_Fortran)
endif()
add_executable(ESMF_ArrayIOTypesUTest  ESMF_ArrayIOTypesUTest.F90)
target_link_libraries(ESMF_ArrayIOTypesUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMF_ArrayIOTypesUTest OpenMP::OpenMP_Fortran)
endif()
add_executable(ESMF_ArrayIOUTest  ESMF_ArrayIOUTest.F90)
target_link_libraries(ESMF_ArrayIOUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMF_ArrayIOUTest OpenMP::OpenMP_Fortran)
endif()
add_executable(ESMF_ArraySMMUTest  ESMF_ArraySMMUTest.F90)
target_link_libraries(ESMF_ArraySMMUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMF_ArraySMMUTest OpenMP::OpenMP_Fortran)
endif()
add_executable(ESMF_ArraySMMFromFileUTest  ESMF_ArraySMMFromFileUTest.F90)
target_link_libraries(ESMF_ArraySMMFromFileUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMF_ArraySMMFromFileUTest OpenMP::OpenMP_Fortran)
endif()
add_executable(ESMF_ArrayArbIdxSMMUTest  ESMF_ArrayArbIdxSMMUTest.F90)
target_link_libraries(ESMF_ArrayArbIdxSMMUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMF_ArrayArbIdxSMMUTest OpenMP::OpenMP_Fortran)
endif()
add_executable(ESMF_ArrayRedistUTest  ESMF_ArrayRedistUTest.F90)
target_link_libraries(ESMF_ArrayRedistUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMF_ArrayRedistUTest OpenMP::OpenMP_Fortran)
endif()
add_executable(ESMF_ArrayRedistPerfUTest  ESMF_ArrayRedistPerfUTest.F90)
target_link_libraries(ESMF_ArrayRedistPerfUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMF_ArrayRedistPerfUTest OpenMP::OpenMP_Fortran)
endif()
add_executable(ESMF_ArrayHaloUTest  ESMF_ArrayHaloUTest.F90)
target_link_libraries(ESMF_ArrayHaloUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMF_ArrayHaloUTest OpenMP::OpenMP_Fortran)
endif()
add_executable(ESMC_ArrayUTest  ESMC_ArrayUTest.c)
target_link_libraries(ESMC_ArrayUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMC_ArrayUTest OpenMP::OpenMP_C)
endif()
add_test(RUN_ESMF_ArrayCreateGetUTest COMMAND ESMF_ArrayCreateGetUTest)
set_property(TEST RUN_ESMF_ArrayCreateGetUTest PROPERTY LABEL MPI )
add_test(RUN_ESMF_ArrayDataUTest COMMAND ESMF_ArrayDataUTest)
set_property(TEST RUN_ESMF_ArrayDataUTest PROPERTY LABEL MPI )
add_test(RUN_ESMF_ArrayScatterUTest COMMAND ESMF_ArrayScatterUTest)
set_property(TEST RUN_ESMF_ArrayScatterUTest PROPERTY LABEL MPI )
add_test(RUN_ESMF_ArrayGatherUTest COMMAND ESMF_ArrayGatherUTest)
set_property(TEST RUN_ESMF_ArrayGatherUTest PROPERTY LABEL MPI )
add_test(RUN_ESMF_ArrayIOTypesUTest COMMAND ESMF_ArrayIOTypesUTest)
set_property(TEST RUN_ESMF_ArrayIOTypesUTest PROPERTY LABEL MPI )
add_test(RUN_ESMF_ArrayIOUTest COMMAND ESMF_ArrayIOUTest)
set_property(TEST RUN_ESMF_ArrayIOUTest PROPERTY LABEL MPI )
add_test(RUN_ESMF_ArraySMMUTest COMMAND ESMF_ArraySMMUTest)
set_property(TEST RUN_ESMF_ArraySMMUTest PROPERTY LABEL MPI )
add_test(RUN_ESMF_ArraySMMFromFileUTest COMMAND ESMF_ArraySMMFromFileUTest)
set_property(TEST RUN_ESMF_ArraySMMFromFileUTest PROPERTY LABEL MPI )
add_test(RUN_ESMF_ArrayArbIdxSMMUTest COMMAND ESMF_ArrayArbIdxSMMUTest)
set_property(TEST RUN_ESMF_ArrayArbIdxSMMUTest PROPERTY LABEL MPI )
add_test(RUN_ESMF_ArrayRedistUTest COMMAND ESMF_ArrayRedistUTest)
set_property(TEST RUN_ESMF_ArrayRedistUTest PROPERTY LABEL MPI )
add_test(RUN_ESMF_ArrayRedistPerfUTest COMMAND ESMF_ArrayRedistPerfUTest)
set_property(TEST RUN_ESMF_ArrayRedistPerfUTest PROPERTY LABEL MPI )
add_test(RUN_ESMF_ArrayHaloUTest COMMAND ESMF_ArrayHaloUTest)
set_property(TEST RUN_ESMF_ArrayHaloUTest PROPERTY LABEL MPI )
add_test(RUN_ESMC_ArrayUTest COMMAND ESMC_ArrayUTest)
set_property(TEST RUN_ESMC_ArrayUTest PROPERTY LABEL MPI )
add_test(RUN_ESMF_ArrayDataUTestUNI COMMAND ESMF_ArrayDataUTest)
set_property(TEST RUN_ESMF_ArrayDataUTestUNI PROPERTY LABEL serial )
add_test(RUN_ESMF_ArrayIOTypesUTestUNI COMMAND ESMF_ArrayIOTypesUTest)
set_property(TEST RUN_ESMF_ArrayIOTypesUTestUNI PROPERTY LABEL serial )
add_test(RUN_ESMF_ArraySMMUTestUNI COMMAND ESMF_ArraySMMUTest)
set_property(TEST RUN_ESMF_ArraySMMUTestUNI PROPERTY LABEL serial )
add_test(RUN_ESMF_ArraySMMFromFileUTestUNI COMMAND ESMF_ArraySMMFromFileUTest)
set_property(TEST RUN_ESMF_ArraySMMFromFileUTestUNI PROPERTY LABEL serial )
add_test(RUN_ESMC_ArrayUTestUNI COMMAND ESMC_ArrayUTest)
set_property(TEST RUN_ESMC_ArrayUTestUNI PROPERTY LABEL serial )
