
target_include_directories(esmf PRIVATE ${ESMF_SOURCE_DIR}/src/Infrastructure/Base/tests/../include)

if(${Git_FOUND})
    string(REGEX REPLACE "^([0-9]+)\.([0-9]+)(\.[0-9]+)?$" "\\1.\\2" ESMF_VERSION_STRING_GIT ${GIT_VERSION_STRING})
    add_compile_definitions(ESMF_VERSION_STRING_GIT="${ESMF_VERSION_STRING_GIT}")
endif()
add_executable(ESMF_BaseUTest  ESMF_BaseUTest.F90)
target_link_libraries(ESMF_BaseUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMF_BaseUTest OpenMP::OpenMP_Fortran)
endif()
add_executable(ESMCI_BaseUTest  ESMCI_BaseUTest.C)
target_link_libraries(ESMCI_BaseUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMCI_BaseUTest OpenMP::OpenMP_CXX)
endif()
add_executable(ESMCI_NlohmannJSONUTest  ESMCI_NlohmannJSONUTest.C)
target_link_libraries(ESMCI_NlohmannJSONUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMCI_NlohmannJSONUTest OpenMP::OpenMP_CXX)
endif()
add_executable(ESMCI_InfoUTest  ESMCI_InfoUTest.C)
target_link_libraries(ESMCI_InfoUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMCI_InfoUTest OpenMP::OpenMP_CXX)
endif()
add_executable(ESMF_InfoUTest  ESMF_InfoUTest.F90)
target_link_libraries(ESMF_InfoUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMF_InfoUTest OpenMP::OpenMP_Fortran)
endif()
add_executable(ESMF_InfoArrayUTest  ESMF_InfoArrayUTest.F90)
target_link_libraries(ESMF_InfoArrayUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMF_InfoArrayUTest OpenMP::OpenMP_Fortran)
endif()
add_test(RUN_ESMF_BaseUTest COMMAND ESMF_BaseUTest)
set_property(TEST RUN_ESMF_BaseUTest PROPERTY LABEL MPI )
add_test(RUN_ESMCI_BaseUTest COMMAND ESMCI_BaseUTest)
set_property(TEST RUN_ESMCI_BaseUTest PROPERTY LABEL MPI )
add_test(RUN_ESMCI_NlohmannJSONUTest COMMAND ESMCI_NlohmannJSONUTest)
set_property(TEST RUN_ESMCI_NlohmannJSONUTest PROPERTY LABEL MPI )
add_test(RUN_ESMCI_InfoUTest COMMAND ESMCI_InfoUTest)
set_property(TEST RUN_ESMCI_InfoUTest PROPERTY LABEL MPI )
add_test(RUN_ESMF_InfoUTest COMMAND ESMF_InfoUTest)
set_property(TEST RUN_ESMF_InfoUTest PROPERTY LABEL MPI )
add_test(RUN_ESMF_InfoArrayUTest COMMAND ESMF_InfoArrayUTest)
set_property(TEST RUN_ESMF_InfoArrayUTest PROPERTY LABEL MPI )
add_test(RUN_ESMF_BaseUTestUNI COMMAND ESMF_BaseUTest)
set_property(TEST RUN_ESMF_BaseUTestUNI PROPERTY LABEL serial )
add_test(RUN_ESMCI_BaseUTestUNI COMMAND ESMCI_BaseUTest)
set_property(TEST RUN_ESMCI_BaseUTestUNI PROPERTY LABEL serial )
add_test(RUN_ESMCI_NlohmannJSONUTestUNI COMMAND ESMCI_NlohmannJSONUTest)
set_property(TEST RUN_ESMCI_NlohmannJSONUTestUNI PROPERTY LABEL serial )
add_test(RUN_ESMCI_InfoUTestUNI COMMAND ESMCI_InfoUTest)
set_property(TEST RUN_ESMCI_InfoUTestUNI PROPERTY LABEL serial )
add_test(RUN_ESMF_InfoUTestUNI COMMAND ESMF_InfoUTest)
set_property(TEST RUN_ESMF_InfoUTestUNI PROPERTY LABEL serial )
add_test(RUN_ESMF_InfoArrayUTestUNI COMMAND ESMF_InfoArrayUTest)
set_property(TEST RUN_ESMF_InfoArrayUTestUNI PROPERTY LABEL serial )
