
target_include_directories(esmf PRIVATE ${ESMF_SOURCE_DIR}/src/Infrastructure/Route/tests/../include)

if(${Git_FOUND})
    string(REGEX REPLACE "^([0-9]+)\.([0-9]+)(\.[0-9]+)?$" "\\1.\\2" ESMF_VERSION_STRING_GIT ${GIT_VERSION_STRING})
    add_compile_definitions(ESMF_VERSION_STRING_GIT="${ESMF_VERSION_STRING_GIT}")
endif()
add_executable(ESMF_RouteHandleUTest  ESMF_RouteHandleUTest.F90)
target_link_libraries(ESMF_RouteHandleUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMF_RouteHandleUTest OpenMP::OpenMP_Fortran)
endif()
add_executable(ESMF_RouteHandleAdvancedUTest  ESMF_RouteHandleAdvancedUTest.F90)
target_link_libraries(ESMF_RouteHandleAdvancedUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMF_RouteHandleAdvancedUTest OpenMP::OpenMP_Fortran)
endif()
add_executable(ESMC_RouteHandleUTest  ESMC_RouteHandleUTest.c)
target_link_libraries(ESMC_RouteHandleUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMC_RouteHandleUTest OpenMP::OpenMP_C)
endif()
add_test(RUN_ESMF_RouteHandleUTest COMMAND ESMF_RouteHandleUTest)
set_property(TEST RUN_ESMF_RouteHandleUTest PROPERTY LABEL MPI )
add_test(RUN_ESMF_RouteHandleAdvancedUTest COMMAND ESMF_RouteHandleAdvancedUTest)
set_property(TEST RUN_ESMF_RouteHandleAdvancedUTest PROPERTY LABEL MPI )
add_test(RUN_ESMC_RouteHandleUTest COMMAND ESMC_RouteHandleUTest)
set_property(TEST RUN_ESMC_RouteHandleUTest PROPERTY LABEL MPI )
add_test(RUN_ESMF_RouteHandleUTestUNI COMMAND ESMF_RouteHandleUTest)
set_property(TEST RUN_ESMF_RouteHandleUTestUNI PROPERTY LABEL serial )
add_test(RUN_ESMC_RouteHandleUTestUNI COMMAND ESMC_RouteHandleUTest)
set_property(TEST RUN_ESMC_RouteHandleUTestUNI PROPERTY LABEL serial )
