
target_include_directories(esmf PRIVATE ${ESMF_SOURCE_DIR}/src/Infrastructure/Field/tests/../include)

if(${Git_FOUND})
    string(REGEX REPLACE "^([0-9]+)\.([0-9]+)(\.[0-9]+)?$" "\\1.\\2" ESMF_VERSION_STRING_GIT ${GIT_VERSION_STRING})
    add_compile_definitions(ESMF_VERSION_STRING_GIT="${ESMF_VERSION_STRING_GIT}")
endif()
add_executable(ESMC_FieldUTest  ESMC_FieldUTest.c)
target_link_libraries(ESMC_FieldUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMC_FieldUTest OpenMP::OpenMP_C)
endif()
add_executable(ESMC_FieldRegridUTest  ESMC_FieldRegridUTest.c)
target_link_libraries(ESMC_FieldRegridUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMC_FieldRegridUTest OpenMP::OpenMP_C)
endif()
add_executable(ESMC_FieldRegridCsrvUTest  ESMC_FieldRegridCsrvUTest.c)
target_link_libraries(ESMC_FieldRegridCsrvUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMC_FieldRegridCsrvUTest OpenMP::OpenMP_C)
endif()
add_executable(ESMC_FieldGridRegridUTest  ESMC_FieldGridRegridUTest.c)
target_link_libraries(ESMC_FieldGridRegridUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMC_FieldGridRegridUTest OpenMP::OpenMP_C)
endif()
add_executable(ESMC_FieldGridRegrid2UTest  ESMC_FieldGridRegrid2UTest.c)
target_link_libraries(ESMC_FieldGridRegrid2UTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMC_FieldGridRegrid2UTest OpenMP::OpenMP_C)
endif()
add_executable(ESMC_FieldGridRegridCsrvUTest  ESMC_FieldGridRegridCsrvUTest.c)
target_link_libraries(ESMC_FieldGridRegridCsrvUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMC_FieldGridRegridCsrvUTest OpenMP::OpenMP_C)
endif()
add_executable(ESMC_FieldGridRegridCsrv2UTest  ESMC_FieldGridRegridCsrv2UTest.c)
target_link_libraries(ESMC_FieldGridRegridCsrv2UTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMC_FieldGridRegridCsrv2UTest OpenMP::OpenMP_C)
endif()
add_executable(ESMC_FieldGridRegridParUTest  ESMC_FieldGridRegridParUTest.c)
target_link_libraries(ESMC_FieldGridRegridParUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMC_FieldGridRegridParUTest OpenMP::OpenMP_C)
endif()
add_executable(ESMC_FieldGridGridRegridUTest  ESMC_FieldGridGridRegridUTest.c)
target_link_libraries(ESMC_FieldGridGridRegridUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMC_FieldGridGridRegridUTest OpenMP::OpenMP_C)
endif()
add_executable(ESMC_FieldGridGridRegridCsrvUTest  ESMC_FieldGridGridRegridCsrvUTest.c)
target_link_libraries(ESMC_FieldGridGridRegridCsrvUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMC_FieldGridGridRegridCsrvUTest OpenMP::OpenMP_C)
endif()
add_executable(ESMC_FieldTripoleRegridUTest  ESMC_FieldTripoleRegridUTest.c)
target_link_libraries(ESMC_FieldTripoleRegridUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMC_FieldTripoleRegridUTest OpenMP::OpenMP_C)
endif()
add_executable(ESMC_FieldSMMFromFileUTest  ESMC_FieldSMMFromFileUTest.c)
target_link_libraries(ESMC_FieldSMMFromFileUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMC_FieldSMMFromFileUTest OpenMP::OpenMP_C)
endif()
add_executable(ESMF_FieldUTest  ESMF_FieldUTest.F90)
target_link_libraries(ESMF_FieldUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMF_FieldUTest OpenMP::OpenMP_Fortran)
endif()
add_executable(ESMF_FieldCreateGetUTest  ESMF_FieldCreateGetUTest.F90)
target_link_libraries(ESMF_FieldCreateGetUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMF_FieldCreateGetUTest OpenMP::OpenMP_Fortran)
endif()
add_executable(ESMF_FieldRegridCsrvUTest  ESMF_FieldRegridCsrvUTest.F90)
target_link_libraries(ESMF_FieldRegridCsrvUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMF_FieldRegridCsrvUTest OpenMP::OpenMP_Fortran)
endif()
add_executable(ESMF_FieldRegridCsrv2ndUTest  ESMF_FieldRegridCsrv2ndUTest.F90)
target_link_libraries(ESMF_FieldRegridCsrv2ndUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMF_FieldRegridCsrv2ndUTest OpenMP::OpenMP_Fortran)
endif()
add_executable(ESMF_FieldRegridUTest  ESMF_FieldRegridUTest.F90)
target_link_libraries(ESMF_FieldRegridUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMF_FieldRegridUTest OpenMP::OpenMP_Fortran)
endif()
add_executable(ESMF_FieldRegridCSUTest  ESMF_FieldRegridCSUTest.F90)
target_link_libraries(ESMF_FieldRegridCSUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMF_FieldRegridCSUTest OpenMP::OpenMP_Fortran)
endif()
add_executable(ESMF_FieldArbGridUTest  ESMF_FieldArbGridUTest.F90)
target_link_libraries(ESMF_FieldArbGridUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMF_FieldArbGridUTest OpenMP::OpenMP_Fortran)
endif()
add_executable(ESMF_FieldIOUTest  ESMF_FieldIOUTest.F90)
target_link_libraries(ESMF_FieldIOUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMF_FieldIOUTest OpenMP::OpenMP_Fortran)
endif()
add_executable(ESMF_FieldRegridXGSMMUTest  ESMF_FieldRegridXGSMMUTest.F90)
target_link_libraries(ESMF_FieldRegridXGSMMUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMF_FieldRegridXGSMMUTest OpenMP::OpenMP_Fortran)
endif()
add_executable(ESMF_FieldRegridXGUTest  ESMF_FieldRegridXGUTest.F90)
target_link_libraries(ESMF_FieldRegridXGUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMF_FieldRegridXGUTest OpenMP::OpenMP_Fortran)
endif()
add_executable(ESMF_FieldStressUTest  ESMF_FieldStressUTest.F90)
target_link_libraries(ESMF_FieldStressUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMF_FieldStressUTest OpenMP::OpenMP_Fortran)
endif()
add_executable(ESMF_FieldGatherUTest  ESMF_FieldGatherUTest.F90)
target_link_libraries(ESMF_FieldGatherUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMF_FieldGatherUTest OpenMP::OpenMP_Fortran)
endif()
add_executable(ESMF_FieldRedistUTest  ESMF_FieldRedistUTest.F90)
target_link_libraries(ESMF_FieldRedistUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMF_FieldRedistUTest OpenMP::OpenMP_Fortran)
endif()
add_executable(ESMF_FieldLSSMMUTest  ESMF_FieldLSSMMUTest.F90)
target_link_libraries(ESMF_FieldLSSMMUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMF_FieldLSSMMUTest OpenMP::OpenMP_Fortran)
endif()
add_executable(ESMF_FieldSMMUTest  ESMF_FieldSMMUTest.F90)
target_link_libraries(ESMF_FieldSMMUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMF_FieldSMMUTest OpenMP::OpenMP_Fortran)
endif()
add_executable(ESMF_FieldRedistArbUTest  ESMF_FieldRedistArbUTest.F90)
target_link_libraries(ESMF_FieldRedistArbUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMF_FieldRedistArbUTest OpenMP::OpenMP_Fortran)
endif()
add_executable(ESMF_FieldMeshSMMUTest  ESMF_FieldMeshSMMUTest.F90)
target_link_libraries(ESMF_FieldMeshSMMUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMF_FieldMeshSMMUTest OpenMP::OpenMP_Fortran)
endif()
add_executable(ESMF_FieldHaloUTest  ESMF_FieldHaloUTest.F90)
target_link_libraries(ESMF_FieldHaloUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMF_FieldHaloUTest OpenMP::OpenMP_Fortran)
endif()
add_executable(ESMF_FieldSMMFromFileUTest  ESMF_FieldSMMFromFileUTest.F90)
target_link_libraries(ESMF_FieldSMMFromFileUTest esmf)
if(ESMF_OPENMP)
target_link_libraries(ESMF_FieldSMMFromFileUTest OpenMP::OpenMP_Fortran)
endif()
add_test(RUN_ESMC_FieldUTest COMMAND ESMC_FieldUTest)
set_property(TEST RUN_ESMC_FieldUTest PROPERTY LABEL MPI )
add_test(RUN_ESMC_FieldRegridUTest COMMAND ESMC_FieldRegridUTest)
set_property(TEST RUN_ESMC_FieldRegridUTest PROPERTY LABEL MPI )
add_test(RUN_ESMC_FieldRegridCsrvUTest COMMAND ESMC_FieldRegridCsrvUTest)
set_property(TEST RUN_ESMC_FieldRegridCsrvUTest PROPERTY LABEL MPI )
add_test(RUN_ESMC_FieldGridRegridUTest COMMAND ESMC_FieldGridRegridUTest)
set_property(TEST RUN_ESMC_FieldGridRegridUTest PROPERTY LABEL MPI )
add_test(RUN_ESMC_FieldGridRegrid2UTest COMMAND ESMC_FieldGridRegrid2UTest)
set_property(TEST RUN_ESMC_FieldGridRegrid2UTest PROPERTY LABEL MPI )
add_test(RUN_ESMC_FieldGridRegridCsrvUTest COMMAND ESMC_FieldGridRegridCsrvUTest)
set_property(TEST RUN_ESMC_FieldGridRegridCsrvUTest PROPERTY LABEL MPI )
add_test(RUN_ESMC_FieldGridRegridCsrv2UTest COMMAND ESMC_FieldGridRegridCsrv2UTest)
set_property(TEST RUN_ESMC_FieldGridRegridCsrv2UTest PROPERTY LABEL MPI )
add_test(RUN_ESMC_FieldGridRegridParUTest COMMAND ESMC_FieldGridRegridParUTest)
set_property(TEST RUN_ESMC_FieldGridRegridParUTest PROPERTY LABEL MPI )
add_test(RUN_ESMC_FieldGridGridRegridUTest COMMAND ESMC_FieldGridGridRegridUTest)
set_property(TEST RUN_ESMC_FieldGridGridRegridUTest PROPERTY LABEL MPI )
add_test(RUN_ESMC_FieldGridGridRegridCsrvUTest COMMAND ESMC_FieldGridGridRegridCsrvUTest)
set_property(TEST RUN_ESMC_FieldGridGridRegridCsrvUTest PROPERTY LABEL MPI )
add_test(RUN_ESMC_FieldSMMFromFileUTest COMMAND ESMC_FieldSMMFromFileUTest)
set_property(TEST RUN_ESMC_FieldSMMFromFileUTest PROPERTY LABEL MPI )
add_test(RUN_ESMF_FieldUTest COMMAND ESMF_FieldUTest)
set_property(TEST RUN_ESMF_FieldUTest PROPERTY LABEL MPI )
add_test(RUN_ESMF_FieldCreateGetUTest COMMAND ESMF_FieldCreateGetUTest)
set_property(TEST RUN_ESMF_FieldCreateGetUTest PROPERTY LABEL MPI )
add_test(RUN_ESMF_FieldRegridUTest COMMAND ESMF_FieldRegridUTest)
set_property(TEST RUN_ESMF_FieldRegridUTest PROPERTY LABEL MPI )
add_test(RUN_ESMF_FieldRegridCSUTest COMMAND ESMF_FieldRegridCSUTest)
set_property(TEST RUN_ESMF_FieldRegridCSUTest PROPERTY LABEL MPI )
add_test(RUN_ESMF_FieldRegridCsrvUTest COMMAND ESMF_FieldRegridCsrvUTest)
set_property(TEST RUN_ESMF_FieldRegridCsrvUTest PROPERTY LABEL MPI )
add_test(RUN_ESMF_FieldRegridCsrv2ndUTest COMMAND ESMF_FieldRegridCsrv2ndUTest)
set_property(TEST RUN_ESMF_FieldRegridCsrv2ndUTest PROPERTY LABEL MPI )
add_test(RUN_ESMF_FieldArbGridUTest COMMAND ESMF_FieldArbGridUTest)
set_property(TEST RUN_ESMF_FieldArbGridUTest PROPERTY LABEL MPI )
add_test(RUN_ESMF_FieldIOUTest COMMAND ESMF_FieldIOUTest)
set_property(TEST RUN_ESMF_FieldIOUTest PROPERTY LABEL MPI )
add_test(RUN_ESMF_FieldStressUTest COMMAND ESMF_FieldStressUTest)
set_property(TEST RUN_ESMF_FieldStressUTest PROPERTY LABEL MPI )
add_test(RUN_ESMF_FieldRegridXGSMMUTest COMMAND ESMF_FieldRegridXGSMMUTest)
set_property(TEST RUN_ESMF_FieldRegridXGSMMUTest PROPERTY LABEL MPI )
add_test(RUN_ESMF_FieldRegridXGUTest COMMAND ESMF_FieldRegridXGUTest)
set_property(TEST RUN_ESMF_FieldRegridXGUTest PROPERTY LABEL MPI )
add_test(RUN_ESMF_FieldGatherUTest COMMAND ESMF_FieldGatherUTest)
set_property(TEST RUN_ESMF_FieldGatherUTest PROPERTY LABEL MPI )
add_test(RUN_ESMF_FieldRedistUTest COMMAND ESMF_FieldRedistUTest)
set_property(TEST RUN_ESMF_FieldRedistUTest PROPERTY LABEL MPI )
add_test(RUN_ESMF_FieldLSSMMUTest COMMAND ESMF_FieldLSSMMUTest)
set_property(TEST RUN_ESMF_FieldLSSMMUTest PROPERTY LABEL MPI )
add_test(RUN_ESMF_FieldSMMUTest COMMAND ESMF_FieldSMMUTest)
set_property(TEST RUN_ESMF_FieldSMMUTest PROPERTY LABEL MPI )
add_test(RUN_ESMF_FieldRedistArbUTest COMMAND ESMF_FieldRedistArbUTest)
set_property(TEST RUN_ESMF_FieldRedistArbUTest PROPERTY LABEL MPI )
add_test(RUN_ESMF_FieldMeshSMMUTest COMMAND ESMF_FieldMeshSMMUTest)
set_property(TEST RUN_ESMF_FieldMeshSMMUTest PROPERTY LABEL MPI )
add_test(RUN_ESMF_FieldHaloUTest COMMAND ESMF_FieldHaloUTest)
set_property(TEST RUN_ESMF_FieldHaloUTest PROPERTY LABEL MPI )
add_test(RUN_ESMF_FieldSMMFromFileUTest COMMAND ESMF_FieldSMMFromFileUTest)
set_property(TEST RUN_ESMF_FieldSMMFromFileUTest PROPERTY LABEL MPI )
add_test(RUN_ESMC_FieldUTestUNI COMMAND ESMC_FieldUTest)
set_property(TEST RUN_ESMC_FieldUTestUNI PROPERTY LABEL serial )
add_test(RUN_ESMC_FieldRegridUTestUNI COMMAND ESMC_FieldRegridUTest)
set_property(TEST RUN_ESMC_FieldRegridUTestUNI PROPERTY LABEL serial )
add_test(RUN_ESMC_FieldRegridCsrvUTestUNI COMMAND ESMC_FieldRegridCsrvUTest)
set_property(TEST RUN_ESMC_FieldRegridCsrvUTestUNI PROPERTY LABEL serial )
add_test(RUN_ESMC_FieldGridRegridUTestUNI COMMAND ESMC_FieldGridRegridUTest)
set_property(TEST RUN_ESMC_FieldGridRegridUTestUNI PROPERTY LABEL serial )
add_test(RUN_ESMC_FieldGridRegrid2UTestUNI COMMAND ESMC_FieldGridRegrid2UTest)
set_property(TEST RUN_ESMC_FieldGridRegrid2UTestUNI PROPERTY LABEL serial )
add_test(RUN_ESMC_FieldGridRegridCsrvUTestUNI COMMAND ESMC_FieldGridRegridCsrvUTest)
set_property(TEST RUN_ESMC_FieldGridRegridCsrvUTestUNI PROPERTY LABEL serial )
add_test(RUN_ESMC_FieldGridRegridCsrv2UTestUNI COMMAND ESMC_FieldGridRegridCsrv2UTest)
set_property(TEST RUN_ESMC_FieldGridRegridCsrv2UTestUNI PROPERTY LABEL serial )
add_test(RUN_ESMC_FieldGridGridRegridUTestUNI COMMAND ESMC_FieldGridGridRegridUTest)
set_property(TEST RUN_ESMC_FieldGridGridRegridUTestUNI PROPERTY LABEL serial )
add_test(RUN_ESMC_FieldSMMFromFileUTestUNI COMMAND ESMC_FieldSMMFromFileUTest)
set_property(TEST RUN_ESMC_FieldSMMFromFileUTestUNI PROPERTY LABEL serial )
add_test(RUN_ESMC_FieldGridGridRegridCsrvUTestUNI COMMAND ESMC_FieldGridGridRegridCsrvUTest)
set_property(TEST RUN_ESMC_FieldGridGridRegridCsrvUTestUNI PROPERTY LABEL serial )
add_test(RUN_ESMF_FieldStressUTestUNI COMMAND ESMF_FieldStressUTest)
set_property(TEST RUN_ESMF_FieldStressUTestUNI PROPERTY LABEL serial )
add_test(RUN_ESMF_FieldRegridUTestUNI COMMAND ESMF_FieldRegridUTest)
set_property(TEST RUN_ESMF_FieldRegridUTestUNI PROPERTY LABEL serial )
add_test(RUN_ESMF_FieldRegridCSUTestUNI COMMAND ESMF_FieldRegridCSUTest)
set_property(TEST RUN_ESMF_FieldRegridCSUTestUNI PROPERTY LABEL serial )
add_test(RUN_ESMF_FieldRegridXGUTestUNI COMMAND ESMF_FieldRegridXGUTest)
set_property(TEST RUN_ESMF_FieldRegridXGUTestUNI PROPERTY LABEL serial )
add_test(RUN_ESMF_FieldArbGridUTestUNI COMMAND ESMF_FieldArbGridUTest)
set_property(TEST RUN_ESMF_FieldArbGridUTestUNI PROPERTY LABEL serial )
add_test(RUN_ESMF_FieldRedistArbUTestUNI COMMAND ESMF_FieldRedistArbUTest)
set_property(TEST RUN_ESMF_FieldRedistArbUTestUNI PROPERTY LABEL serial )
add_test(RUN_ESMF_FieldRegridCsrvUTestUNI COMMAND ESMF_FieldRegridCsrvUTest)
set_property(TEST RUN_ESMF_FieldRegridCsrvUTestUNI PROPERTY LABEL serial )
add_test(RUN_ESMF_FieldRegridCsrv2ndUTestUNI COMMAND ESMF_FieldRegridCsrv2ndUTest)
set_property(TEST RUN_ESMF_FieldRegridCsrv2ndUTestUNI PROPERTY LABEL serial )
add_test(RUN_ESMF_FieldSMMFromFileUTestUNI COMMAND ESMF_FieldSMMFromFileUTest)
set_property(TEST RUN_ESMF_FieldSMMFromFileUTestUNI PROPERTY LABEL serial )
